/**
 * Cross-implementation fixtures for Twilio webhook signature verification.
 *
 * Every `signature` below was generated by the **Twilio Python SDK's**
 * `RequestValidator.compute_signature` — the implementation the FastAPI service
 * verifies against today — using the token and base URL in this file. They are
 * not round-trip values produced by the code under test, which is the point: a
 * round-trip test passes happily against an HMAC that agrees with nothing but
 * itself, and would not have caught an ordering, encoding, or URL-assembly
 * difference between the two runtimes.
 *
 * Regenerate with (from `apps/api`, with the Python venv):
 *
 *     .venv/bin/python -c "from twilio.request_validator import RequestValidator; \
 *       print(RequestValidator('<token>').compute_signature('<url>', <params>))"
 */

import { describe, expect, it } from 'vitest'

import { TwilioWebhookVerifier } from '../signatures'

const AUTH_TOKEN = 'test_auth_token_0123456789abcdef'
const BASE_URL = 'https://api.876.app/webhooks'

function verifier(
  overrides: { authToken?: string; webhookBaseUrl?: string } = {}
) {
  return new TwilioWebhookVerifier({
    authToken: overrides.authToken ?? AUTH_TOKEN,
    webhookBaseUrl: overrides.webhookBaseUrl ?? BASE_URL,
  })
}

const VECTORS: ReadonlyArray<{
  label: string
  path: string
  params: Record<string, string>
  signature: string
}> = [
  {
    label: 'a message status callback',
    path: '/twilio/status',
    params: { MessageSid: 'SM123', MessageStatus: 'delivered' },
    signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
  },
  {
    label: 'a call status callback carrying a query string',
    path: 'twilio/status?attempt=2',
    params: { CallSid: 'CA1', CallStatus: 'completed', From: '+18765550123' },
    signature: 'f8/buvHvOTsamP7NYcMtkIXKwRk=',
  },
  {
    label: 'a callback with no parameters',
    path: '/twilio/inbound',
    params: {},
    signature: 'Bgg7Y6NSK9NCZnngbiJiZMpB7VU=',
  },
  {
    label: 'parameters that are not in sorted order, including an empty value',
    path: '/twilio/x',
    params: { b: '2', a: '1', C: '3', _z: '', A: 'x' },
    signature: 'H95VUk8KIRSJgWDR2wK6hmVm2BM=',
  },
]

describe('TwilioWebhookVerifier', () => {
  it.each(VECTORS)(
    'accepts a Twilio-SDK signature for $label',
    ({ path, params, signature }) => {
      expect(verifier().validate({ path, params, signature })).toBe(true)
    }
  )

  it('accepts a leading-slash and a bare path identically', () => {
    const [vector] = VECTORS
    expect(
      verifier().validate({
        path: vector!.path.replace(/^\//, ''),
        params: vector!.params,
        signature: vector!.signature,
      })
    ).toBe(true)
  })

  it('accepts a base URL configured with a trailing slash', () => {
    const [vector] = VECTORS
    expect(
      verifier({ webhookBaseUrl: `${BASE_URL}/` }).validate({
        path: vector!.path,
        params: vector!.params,
        signature: vector!.signature,
      })
    ).toBe(true)
  })

  it('rejects a tampered parameter value', () => {
    expect(
      verifier().validate({
        path: '/twilio/status',
        params: { MessageSid: 'SM123', MessageStatus: 'undelivered' },
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })

  it('rejects an added parameter', () => {
    expect(
      verifier().validate({
        path: '/twilio/status',
        params: { MessageSid: 'SM123', MessageStatus: 'delivered', Extra: '1' },
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })

  it('rejects a signature computed for a different path', () => {
    expect(
      verifier().validate({
        path: '/twilio/other',
        params: { MessageSid: 'SM123', MessageStatus: 'delivered' },
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })

  it('rejects a signature computed against a different base URL', () => {
    // The whole reason the base URL is configured rather than reconstructed:
    // an attacker who could choose the host could choose the signed string.
    expect(
      verifier({
        webhookBaseUrl: 'https://evil.example.com/webhooks',
      }).validate({
        path: '/twilio/status',
        params: { MessageSid: 'SM123', MessageStatus: 'delivered' },
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })

  it('rejects a signature computed with a different auth token', () => {
    expect(
      verifier({ authToken: 'a_different_token_0123456789abcd' }).validate({
        path: '/twilio/status',
        params: { MessageSid: 'SM123', MessageStatus: 'delivered' },
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })

  it('rejects every request when the auth token is unset', () => {
    // Unset must never mean allow.
    expect(
      verifier({ authToken: '' }).validate({
        path: '/twilio/status',
        params: { MessageSid: 'SM123', MessageStatus: 'delivered' },
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })

  it.each([
    ['an empty signature', ''],
    ['a malformed signature', 'not-base64!!'],
    ['a truncated signature', 'h724dseAzZ4F8D25zN+Tp'],
  ])('rejects %s', (_label, signature) => {
    expect(
      verifier().validate({
        path: '/twilio/status',
        params: { MessageSid: 'SM123', MessageStatus: 'delivered' },
        signature,
      })
    ).toBe(false)
  })

  it('rejects rather than throwing on an unparseable path', () => {
    expect(
      verifier({ webhookBaseUrl: 'not a url' }).validate({
        path: '/twilio/status',
        params: {},
        signature: 'h724dseAzZ4F8D25zN+TpFZqqtY=',
      })
    ).toBe(false)
  })
})
