import type { Request, Response } from 'express'
import { sendWorkError, sendWorkList, sendWorkResult } from '../../http/result.js'
import * as service from './calendars.service.js'
import { calendarParamsSchema, createCalendarBodySchema, deleteCalendarBodySchema, listCalendarsQuerySchema, organizationParamsSchema, updateCalendarBodySchema } from './calendars.schemas.js'
export async function listCalendars(req: Request, res: Response) { const { organizationId } = organizationParamsSchema.parse(req.params); const q = listCalendarsQuerySchema.parse(req.query); return sendWorkList(res, await service.list(organizationId, { ...(q.user_id ? { userId: q.user_id } : {}), ...(q.visibility ? { visibility: q.visibility } : {}), limit: q.limit, ...(q.starting_after ? { startingAfter: q.starting_after } : {}), ...(q.ending_before ? { endingBefore: q.ending_before } : {}) }), `/v1/organizations/${organizationId}/calendars`) }
export async function retrieveCalendar(req: Request, res: Response) { const { organizationId, calendarId } = calendarParamsSchema.parse(req.params); const result = await service.retrieve(organizationId, calendarId); if (!result) return sendWorkError(res, 'work/calendar-not-found'); return sendWorkResult(res, result) }
export async function createCalendar(req: Request, res: Response) { const { organizationId } = organizationParamsSchema.parse(req.params); return sendWorkResult(res, await service.create(organizationId, createCalendarBodySchema.parse(req.body)), 201) }
export async function updateCalendar(req: Request, res: Response) { const { organizationId, calendarId } = calendarParamsSchema.parse(req.params); const result = await service.update(organizationId, calendarId, updateCalendarBodySchema.parse(req.body)); if (!result) return sendWorkError(res, 'work/calendar-not-found'); return sendWorkResult(res, result) }
export async function deleteCalendar(req: Request, res: Response) { const { organizationId, calendarId } = calendarParamsSchema.parse(req.params); const { deletedBy } = deleteCalendarBodySchema.parse(req.body); const result = await service.remove(organizationId, calendarId, deletedBy); if (!result) return sendWorkError(res, 'work/calendar-not-found'); return sendWorkResult(res, result) }
