import { getError, isError } from '@876/core'
import type { CreateWorkCalendarInput, UpdateWorkCalendarInput, WorkCalendar } from '@876/work'
import * as tenants from '../tenants/index.js'
import * as repository from './calendars.repository.js'

type Row = Awaited<ReturnType<typeof repository.list>>[number]
const stamp = (value: Date) => Math.floor(value.getTime() / 1000)
function serialize(row: Row, organizationId: string): WorkCalendar {
  return { object: 'calendar', id: row.id, uid: row.uid, organizationId, ownerUserId: row.ownerUserId, name: row.name, description: row.description, timeZone: row.timeZone, visibility: row.visibility, isPrimary: row.isPrimary, createdBy: row.createdBy, createdAt: stamp(row.createdAt), updatedAt: stamp(row.updatedAt) }
}
async function requireTenant(organizationId: string) { const tenant = await tenants.retrieveByOrganization(organizationId); if (!tenant) return getError('work/tenant-not-found'); if (tenant.status !== 'ACTIVE') return getError('work/tenant-inactive'); return tenant }
export async function list(organizationId: string, filter: { userId?: string; visibility?: string; limit?: number; startingAfter?: string; endingBefore?: string } = {}) { const tenant = await requireTenant(organizationId); if (isError(tenant)) return tenant; const limit = filter.limit ?? 25; const rows = await repository.list(tenant.id, { ...filter, limit }); const page = rows.slice(0, limit); return { data: (filter.endingBefore ? page.reverse() : page).map((row) => serialize(row, organizationId)), hasMore: rows.length > limit } }
export async function retrieve(organizationId: string, calendarId: string) { const tenant = await requireTenant(organizationId); if (isError(tenant)) return tenant; const row = await repository.retrieve(tenant.id, calendarId); return row ? serialize(row, organizationId) : null }
export async function create(organizationId: string, input: CreateWorkCalendarInput) { const tenant = await requireTenant(organizationId); if (isError(tenant)) return tenant; const row = await repository.create({ tenantId: tenant.id, ownerUserId: input.ownerUserId ?? null, name: input.name, description: input.description ?? null, timeZone: input.timeZone, visibility: input.visibility ?? 'PRIVATE', isPrimary: false, createdBy: input.createdBy }); return serialize(row, organizationId) }
export async function ensurePrimary(organizationId: string, userId: string, timeZone = 'UTC') { const tenant = await requireTenant(organizationId); if (isError(tenant)) return tenant; const existing = await repository.primaryForUser(tenant.id, userId); if (existing) return serialize(existing, organizationId); return create(organizationId, { ownerUserId: userId, name: 'Calendar', timeZone, visibility: 'PRIVATE', createdBy: userId }) }
export async function update(organizationId: string, calendarId: string, input: UpdateWorkCalendarInput) { const tenant = await requireTenant(organizationId); if (isError(tenant)) return tenant; const current = await repository.retrieve(tenant.id, calendarId); if (!current) return null; const row = await repository.update(calendarId, { ...(input.name === undefined ? {} : { name: input.name }), ...(input.description === undefined ? {} : { description: input.description }), ...(input.timeZone === undefined ? {} : { timeZone: input.timeZone }), ...(input.visibility === undefined ? {} : { visibility: input.visibility }) }); return serialize(row, organizationId) }
export async function remove(organizationId: string, calendarId: string, deletedBy: string) { const tenant = await requireTenant(organizationId); if (isError(tenant)) return tenant; const current = await repository.retrieve(tenant.id, calendarId); if (!current) return null; if (current.isPrimary) return getError('work/calendar-primary-delete-forbidden'); return repository.remove(calendarId, deletedBy) }
