import { beforeEach, describe, expect, it, vi } from 'vitest'
import { BILLING_COMMERCIAL_MODULE_KEYS, INVOICE_COMMERCIAL_MODULE_KEYS, PROJECTS_COMMERCIAL_MODULE_KEYS, findAppModule } from '@876/core/modules'
const repository=vi.hoisted(()=>({createApplicationModule:vi.fn(),findAppBySlug:vi.fn(),findApplicationModule:vi.fn(),findOwnerOrganizationId:vi.fn(),findPriceForProduct:vi.fn(),findProductBySlug:vi.fn(),getSubscription:vi.fn(),listApps:vi.fn(),listFeatures:vi.fn(),listProducts:vi.fn(),listSubscriptionsByApp:vi.fn(),provisionSubscription:vi.fn(),setSubscriptionPrice:vi.fn(),updateApplicationModuleIdentity:vi.fn()}));vi.mock('./plans.repository',()=>repository);vi.mock('@/platform/ids',()=>({generateId:vi.fn((t:string)=>`${t}_generated`)}));vi.mock('@/platform/timestamps',()=>({nowUnixSeconds:vi.fn(()=>1_700_000_000)}));vi.mock('@/platform/logger',()=>({getLogger:vi.fn(()=>({info:vi.fn(),warn:vi.fn(),error:vi.fn()}))}))
import { INVOICE_FREE_PLAN_MODULE_KEYS, INVOICE_FREE_PLAN_SLUG, PLATFORM_MODULES, PROJECTS_FREE_PLAN_MODULE_KEYS, PROJECTS_FREE_PLAN_SLUG, seedPlatformPlanModules } from './plans'
function createdModule(p:{appId:string;key:string;name:string;description:string;featureId:string|null}){return{id:`mod_${p.key}`,...p}}
describe('canonical plan module seed definitions',()=>{beforeEach(()=>{vi.clearAllMocks();repository.listApps.mockResolvedValue([]);repository.listFeatures.mockResolvedValue([]);repository.listProducts.mockResolvedValue([]);repository.findApplicationModule.mockResolvedValue(null);repository.updateApplicationModuleIdentity.mockResolvedValue(undefined);repository.createApplicationModule.mockImplementation((p:Parameters<typeof createdModule>[0])=>Promise.resolve(createdModule(p)))})
it('materializes the exact Invoice commercial registry without crm',()=>{const defs=PLATFORM_MODULES.filter((d)=>d.appSlug==='876-invoice'&&d.syncIdentity);expect(defs.map((d)=>d.key)).toEqual(INVOICE_COMMERCIAL_MODULE_KEYS);for(const d of defs){const c=findAppModule('876-invoice',d.key);expect(d.name).toBe(c?.label);expect(d.description).toBe(c?.description)}expect(defs.some((d)=>d.key==='crm')).toBe(false)})
it('materializes only Projects capabilities with current commercial semantics',()=>{const keys=PLATFORM_MODULES.filter((d)=>d.appSlug==='876-projects'&&d.syncIdentity).map((d)=>d.key);expect(keys).toEqual(PROJECTS_COMMERCIAL_MODULE_KEYS);expect(keys).toEqual(['projects','issues']);expect(keys).not.toContain('reports')})
it('does not materialize Commerce capabilities before runtime module gates exist',()=>expect(PLATFORM_MODULES.filter((d)=>d.appSlug==='876-commerce')).toEqual([]))
it('binds Requests to app-scoped rollout flags in both finance apps',()=>expect(PLATFORM_MODULES.filter((d)=>d.key==='requests').map((d)=>({appSlug:d.appSlug,featureSlug:d.featureSlug,includeCurrentAppPlans:d.includeCurrentAppPlans}))).toEqual([{appSlug:'876-invoice',featureSlug:'invoice-requests',includeCurrentAppPlans:true},{appSlug:'876-billing',featureSlug:'billing-requests',includeCurrentAppPlans:true}]))
it('keeps Billing sales and documents as explicit legacy modules',()=>expect(PLATFORM_MODULES.filter((d)=>d.appSlug==='876-billing'&&!d.syncIdentity).map((d)=>({key:d.key,featureSlug:d.featureSlug}))).toEqual([{key:'sales',featureSlug:'billing-sales'},{key:'documents',featureSlug:'billing-documents'}]))
it('preserves established Billing positions and appends Requests',()=>{const m=new Map(PLATFORM_MODULES.filter((d)=>d.appSlug==='876-billing'&&d.syncIdentity).map((d)=>[d.key,d.position]));expect({subscriptions:m.get('subscriptions'),purchases:m.get('purchases'),banking:m.get('banking'),payroll:m.get('payroll'),requests:m.get('requests')}).toEqual({subscriptions:20,purchases:30,banking:40,payroll:60,requests:70})})
it('grants new Invoice Requests to the current plan beside the free baseline',async()=>{repository.listApps.mockResolvedValue([{id:'app_invoice',slug:'876-invoice'}]);repository.listProducts.mockResolvedValue([{id:'product_invoice_free',slug:INVOICE_FREE_PLAN_SLUG,appId:'app_invoice'}]);const result=await seedPlatformPlanModules();expect(result.planModulesCreated).toBe(INVOICE_FREE_PLAN_MODULE_KEYS.length+1);expect(repository.createApplicationModule).toHaveBeenCalledTimes(INVOICE_COMMERCIAL_MODULE_KEYS.length)})
it('creates Projects modules with initial grants to its free plan',async()=>{repository.listApps.mockResolvedValue([{id:'app_projects',slug:'876-projects'}]);repository.listProducts.mockResolvedValue([{id:'product_projects_free',slug:PROJECTS_FREE_PLAN_SLUG,appId:'app_projects'}]);const result=await seedPlatformPlanModules();expect(result).toEqual({modulesCreated:PROJECTS_COMMERCIAL_MODULE_KEYS.length,planModulesCreated:PROJECTS_FREE_PLAN_MODULE_KEYS.length,billingAssignments:0,ownerProvisioned:false});expect(repository.createApplicationModule.mock.calls.map(([p])=>({key:p.key,grants:p.initialGrants}))).toEqual(PROJECTS_COMMERCIAL_MODULE_KEYS.map((key)=>({key,grants:[{id:'planModule_generated',productId:'product_projects_free'}]})))})
it('grants new Billing Requests to every current Billing plan only',async()=>{repository.listApps.mockResolvedValue([{id:'app_billing',slug:'876-billing'}]);repository.listFeatures.mockResolvedValue([{id:'feat_requests',slug:'billing-requests'}]);repository.listProducts.mockResolvedValue([{id:'plan_free',slug:'billing-free',appId:'app_billing'},{id:'plan_pro',slug:'billing-pro',appId:'app_billing'},{id:'plan_invoice',slug:'invoice-free',appId:'app_invoice'}]);await seedPlatformPlanModules();const call=repository.createApplicationModule.mock.calls.find(([p])=>p.key==='requests');expect(call?.[0]).toEqual(expect.objectContaining({appId:'app_billing',key:'requests',featureId:'feat_requests',initialGrants:[{id:'planModule_generated',productId:'plan_free'},{id:'planModule_generated',productId:'plan_pro'}]}));expect(repository.createApplicationModule.mock.calls.filter(([p])=>p.appId==='app_billing').map(([p])=>p.key)).toEqual([...BILLING_COMMERCIAL_MODULE_KEYS,'sales','documents'])})
it('does not restore a removed Requests grant after the module already exists',async()=>{repository.listApps.mockResolvedValue([{id:'app_invoice',slug:'876-invoice'}]);repository.listProducts.mockResolvedValue([{id:'product_invoice_free',slug:INVOICE_FREE_PLAN_SLUG,appId:'app_invoice'}]);repository.findApplicationModule.mockImplementation((_a:string,key:string)=>{const d=findAppModule('876-invoice',key);return Promise.resolve(d?{id:`mod_${key}`,appId:'app_invoice',key,name:d.label,description:d.description,featureId:null}:null)});const result=await seedPlatformPlanModules();expect(result.modulesCreated).toBe(0);expect(result.planModulesCreated).toBe(0);expect(repository.createApplicationModule).not.toHaveBeenCalled()})
it('repairs stale registry-owned labels and descriptions without changing grants',async()=>{repository.listApps.mockResolvedValue([{id:'app_invoice',slug:'876-invoice'}]);repository.findApplicationModule.mockImplementation((_a:string,key:string)=>Promise.resolve({id:`mod_${key}`,appId:'app_invoice',key,name:'Stale name',description:'Stale description',featureId:null}));const result=await seedPlatformPlanModules();expect(result.planModulesCreated).toBe(0);expect(repository.updateApplicationModuleIdentity).toHaveBeenCalledTimes(INVOICE_COMMERCIAL_MODULE_KEYS.length);expect(repository.createApplicationModule).not.toHaveBeenCalled()})
})
