import { PanelError, PanelFrame, PanelRowsSkeleton } from './panel-frame'
import type { PanelProps, PanelState } from './panel'

export interface CustomerStatementRow { id: string; date: string; description: string; amount: string; balance: string }
export interface CustomerStatement { currency: string; openingBalance: string; rows: CustomerStatementRow[]; closingBalance: string }
export function CustomerStatementPanel({ state, ...props }: PanelProps & { state: PanelState<CustomerStatement> }) {
  return <PanelFrame title="Account statement" {...props}>{state.status === 'ready' ? <div className="space-y-4"><Balance label="Opening balance" value={state.data.openingBalance} currency={state.data.currency} />{state.data.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="text-muted-foreground border-b text-left"><tr><th className="pb-3 font-medium">Date</th><th className="pb-3 font-medium">Activity</th><th className="pb-3 text-right font-medium">Amount</th><th className="pb-3 text-right font-medium">Balance</th></tr></thead><tbody>{state.data.rows.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="py-3">{row.date}</td><td className="py-3">{row.description}</td><td className="py-3 text-right tabular-nums">{row.amount}</td><td className="py-3 text-right tabular-nums">{row.balance}</td></tr>)}</tbody></table></div> : <p className="text-muted-foreground py-3 text-sm">No posted account activity yet.</p>}<Balance label="Closing balance" value={state.data.closingBalance} currency={state.data.currency} /></div> : state.status === 'empty' ? <p className="text-muted-foreground py-4 text-sm">No statement is available for this customer.</p> : <PanelError error={state} />}</PanelFrame>
}
export function CustomerStatementPanelSkeleton() { return <PanelFrame title="Account statement"><PanelRowsSkeleton rows={4} /></PanelFrame> }
function Balance({ label, value, currency }: { label: string; value: string; currency: string }) { return <div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">{label}</span><span className="font-medium tabular-nums">{value} <span className="text-muted-foreground text-xs">{currency}</span></span></div> }
