export const bankingEngineDocs = {
  listStatementImports: { summary: 'List bank statement imports' },
  createStatementImport: { summary: 'Import normalized bank statement lines' },
  retrieveStatementImport: { summary: 'Retrieve a bank statement import' },
  undoStatementImport: { summary: 'Undo an unresolved bank statement import' },
  listStatementLines: { summary: 'List external bank statement lines' },
  retrieveStatementLine: { summary: 'Retrieve an external bank statement line' },
  listMatchCandidates: { summary: 'List candidate booked cash matches' },
  matchStatementLine: { summary: 'Match a statement line to booked cash' },
  unmatchStatementLine: { summary: 'Reverse a statement-line match' },
  categorizeStatementLine: { summary: 'Book and categorize a statement line' },
  excludeStatementLine: { summary: 'Exclude a statement line from review' },
  restoreStatementLine: { summary: 'Restore an excluded statement line' },
  listTransfers: { summary: 'List bank transfers' },
  createTransfer: { summary: 'Create a same-currency bank transfer' },
  listDeposits: { summary: 'List bank deposits' },
  createDeposit: { summary: 'Record a deposit from a holding account' },
  retrieveDeposit: { summary: 'Retrieve a bank deposit' },
  voidDeposit: { summary: 'Void a recorded bank deposit' },
  listReconciliations: { summary: 'List bank reconciliation periods' },
  createReconciliation: { summary: 'Create a bank reconciliation draft' },
  retrieveReconciliation: { summary: 'Retrieve a bank reconciliation' },
  completeReconciliation: { summary: 'Complete a zero-difference reconciliation' },
  reopenReconciliation: { summary: 'Reopen the latest completed reconciliation' },
  listRules: { summary: 'List bank recognition rules' },
  createRule: { summary: 'Create a bank recognition rule' },
  retrieveRule: { summary: 'Retrieve a bank recognition rule' },
  updateRule: { summary: 'Update a bank recognition rule' },
  deleteRule: { summary: 'Delete an unused bank recognition rule' },
} as const
