export const BILLING_PERMISSION_VALUES = [
  'billing:access',
  'dashboard:read',
  'customers:read',
  'customers:write',
  'catalog:read',
  'catalog:write',
  'sales:read',
  'sales:write',
  'sales-orders:read',
  'sales-orders:write',
  'subscriptions:read',
  'subscriptions:write',
  'reports:read',
  'settings:read',
  'currencies:read',
  'currencies:write',
  'taxes:read',
  'taxes:write',
  'members:read',
  'members:write',
  'roles:read',
  'roles:write',
  'vendors:read',
  'vendors:write',
  'purchases:read',
  'purchases:write',
  'banking:read',
  'banking:write',
  'payments:read',
  'payments:write',
  // billing-api is authoritative until Billing moves onto the platform
  // app-access plane, where this duplicated catalog will be removed.
  'payment_methods:read',
  'payment_methods:write',
] as const
