/**
 * The 876 Auth SDK entry point.
 *
 * @module 876
 */

export { create876Client } from './client.ts'
export { isDefault, isExpired } from './helpers/index.ts'
export type { SDK876AuthClient, SDK876Client } from './client.ts'
export { createSignInWith876, generatePkce } from './oauth.ts'
export type { OAuthClient, SignInWith876Options } from './oauth.ts'
export {
  createAuthError,
  createOAuthError,
  createSdkError,
  getInvalidCredentialsMessage,
  mapOAuthErrorCode,
} from './errors.ts'
export type {
  SdkAuthErrorCode,
  SdkError,
  SdkErrorCode,
  SdkErrorDef,
  SdkOAuthErrorCode,
} from './errors.ts'
export type {
  AuthCredentials,
  AuthError,
  AuthErrorCode,
  ClientOptions,
  OAuthOptions,
  RequestOptions,
  Result,
} from './types/api.ts'
export type {
  AuthEvent,
  AuthEventType,
  AuthMethod,
  Email,
  GetSessionResponse,
  GetSessionResult,
  ListProvidersResponse,
  ListProvidersResult,
  LoginParams,
  LoginResponse,
  LoginResult,
  Logout,
  LogoutParams,
  LogoutResponse,
  LogoutResult,
  PasswordRecovery,
  PasswordReset,
  ProviderInfo,
  RecoverParams,
  RecoverResponse,
  RecoverResult,
  Redirect,
  RegisterBusinessParams,
  RegisterBusinessResult,
  RegisterParams,
  RegisterResponse,
  RegisterResult,
  ResetPasswordParams,
  ResetPasswordResponse,
  ResetPasswordResult,
  ResolveParams,
  ResolveResponse,
  ResolveResult,
  ScreenHint,
  SendMagicOtpParams,
  SendMagicOtpResponse,
  SendMagicOtpResult,
  Session,
  SessionMeta,
  SocialLoginParams,
  SocialLoginResponse,
  SocialLoginResult,
  SocialProvider,
  User,
  VerifyEmailCodeParams,
  VerifyEmailCodeResponse,
  VerifyEmailCodeResult,
  VerifyMagicOtpParams,
  VerifyMagicOtpResponse,
  VerifyMagicOtpResult,
} from './types/auth.ts'
export type {
  App,
  AppCreateParams,
  AppCreatedResult,
  AppCreated,
  AppList,
  AppListParams,
  AppListResult,
  AppResult,
} from './types/apps.ts'
export type {
  AuditEvent,
  AuditEventCreateParams,
  AuditEventList,
  AuditEventListResult,
  AuditEventResult,
} from './types/audit-events.ts'
export type {
  OAuthGrant,
  OAuthGrantListResult,
  RevokeOAuthGrantResponse,
  RevokeOAuthGrantResult,
} from './types/oauth-grants.ts'
export type {
  ConsumerAddress,
  ConsumerAddressCreateParams,
  ConsumerAddressList,
  ConsumerAddressListResult,
  ConsumerAddressResult,
  ConsumerAddressUpdateParams,
  ConsumerContact,
  ConsumerContactCreateParams,
  ConsumerContactList,
  ConsumerContactListResult,
  ConsumerContactResult,
  ConsumerContactUpdateParams,
  ConsumerContactUser,
  ConsumerProfile,
  ConsumerProfileResult,
  ConsumerProfileUpdateParams,
  DeletedConsumerAddress,
  DeletedConsumerAddressResult,
  DeletedConsumerContact,
  DeletedConsumerContactResult,
  Gender,
} from './types/users.ts'
export type {
  AuthorizationUrlParams,
  DiscoveryDocument,
  IntrospectParams,
  IntrospectResponse,
  OAuthError,
  OAuthErrorCode,
  OAuthResult,
  PkcePair,
  RefreshTokenParams,
  RevokeParams,
  RevokeResponse,
  TokenParams,
  TokenResponse,
  UserInfo,
  UserInfoParams,
} from './types/oauth.ts'
export type {
  DeletedEmployeeProfile,
  DeletedOrgDepartment,
  DeletedOrgLocation,
  EmployeeProfile,
  EmployeeProfileCreateParams,
  EmployeeProfileList,
  EmployeeProfileUpdateParams,
  Organization,
  OrganizationSelfUpdateParams,
  OrgDepartment,
  OrgDepartmentCreateParams,
  OrgDepartmentList,
  OrgDepartmentUpdateParams,
  OrgLocation,
  OrgLocationCreateParams,
  OrgLocationList,
  OrgLocationUpdateParams,
} from './types/orgs.ts'
export type {
  Price,
  Product,
  ProductList,
  ProductResult,
  ProductListResult,
} from './types/products.ts'
export type {
  SubscriptionItem,
  Subscription,
  SubscriptionList,
  BillingAccount,
  BillingAccountList,
  SubscriptionResult,
  SubscriptionListResult,
  BillingAccountResult,
  BillingAccountListResult,
} from './types/billing.ts'
