ports:
  - port: 3000
    name: 876 App
    visibility: public
    onOpen: notify
  - port: 3001
    name: 876 Enterprise
    visibility: public
    onOpen: notify
  - port: 3002
    name: 876 Console
    visibility: public
    onOpen: notify
  - port: 3003
    name: 876 Couriers
    visibility: public
    onOpen: notify
  - port: 3004
    name: 876 Billing
    visibility: public
    onOpen: notify
  - port: 3005
    name: 876 Widgets API
    visibility: public
    onOpen: notify
  - port: 4000
    name: API
    visibility: public
    onOpen: notify
  - port: 4004
    name: Billing API
    visibility: public
    onOpen: notify
