export { create876CrmClient } from './client'
export type { CrmClient } from './client'
export type {
  ClientOptions,
  ClientError,
  Result,
  Customer,
  CustomerList,
  CustomerProfile,
  CustomerProfileStatus,
  RegistryCustomer,
  CreateCustomerInput,
  UpdateCustomerInput,
  CrmRequest,
  RequestList,
  ListRequestsQuery,
  RequestStatus,
  RequestPriority,
  RequestCategory,
  RequestSource,
  RequestNoteKind,
  CreateRequestInput,
  UpdateRequestInput,
  DeleteInput,
  Deleted,
  CrmRequestNote,
  RequestNoteList,
  CreateRequestNoteInput,
  UpdateRequestNoteInput,
  DeleteRequestNoteInput,
} from './types'
