import { defineModuleCatalog, type ModuleDefinition } from '@876/settings'

export const COURIERS_MODULE_CATALOG = defineModuleCatalog([
  {
    key: 'general',
    label: 'General',
    optional: false,
    enabledByDefault: true,
    preferences: [
      {
        key: 'date-format',
        label: 'Date format',
        type: 'enum',
        default: 'dd/mm/yyyy',
        options: [
          { value: 'dd/mm/yyyy', label: 'DD/MM/YYYY' },
          { value: 'mm/dd/yyyy', label: 'MM/DD/YYYY' },
          { value: 'yyyy-mm-dd', label: 'YYYY-MM-DD' },
        ],
      },
      {
        key: 'timezone',
        label: 'Timezone',
        type: 'string',
        default: 'America/Jamaica',
        maxLength: 64,
      },
      {
        key: 'weight-unit',
        label: 'Weight unit',
        type: 'enum',
        default: 'lb',
        options: [
          { value: 'lb', label: 'Pounds (lb)' },
          { value: 'kg', label: 'Kilograms (kg)' },
        ],
      },
      {
        key: 'dimension-unit',
        label: 'Dimension unit',
        type: 'enum',
        default: 'in',
        options: [
          { value: 'in', label: 'Inches (in)' },
          { value: 'cm', label: 'Centimeters (cm)' },
        ],
      },
      {
        key: 'base-currency',
        label: 'Base currency',
        type: 'reference',
        default: 'JMD',
        namespace: 'currency',
      },
    ],
  },
  {
    key: 'customers',
    label: 'Customers',
    optional: false,
    enabledByDefault: true,
    preferences: [
      {
        key: 'auto-assign-home-branch',
        label: 'Auto-assign home branch',
        type: 'boolean',
        default: true,
        hint: 'Assign new customers to the default branch.',
      },
      {
        key: 'mailbox-auto-assign',
        label: 'Auto-assign mailbox',
        type: 'boolean',
        default: true,
      },
      {
        key: 'mailbox-number-length',
        label: 'Mailbox number length',
        type: 'integer',
        default: 5,
        min: 3,
        max: 10,
      },
      {
        key: 'require-identification',
        label: 'Require identification',
        type: 'boolean',
        default: false,
        hint: 'Require a verified ID before releasing packages.',
      },
      {
        key: 'allow-duplicate-email',
        label: 'Allow duplicate email',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    key: 'items',
    label: 'Items',
    optional: true,
    enabledByDefault: true,
    preferences: [
      {
        key: 'track-inventory',
        label: 'Track inventory',
        type: 'boolean',
        default: false,
      },
      {
        key: 'default-category',
        label: 'Default category',
        type: 'reference',
        default: 'general',
        namespace: 'package-category',
      },
    ],
  },
  {
    key: 'packages',
    label: 'Packages',
    optional: false,
    enabledByDefault: true,
    preferences: [
      {
        key: 'volumetric-divisor',
        label: 'Volumetric divisor',
        type: 'integer',
        default: 5000,
        min: 1000,
        max: 10000,
        hint: '5000 for courier, 6000 for air freight.',
      },
      {
        key: 'chargeable-weight-rule',
        label: 'Chargeable weight rule',
        type: 'enum',
        default: 'greater-of',
        options: [
          { value: 'greater-of', label: 'Greater of actual or volumetric' },
          { value: 'actual-only', label: 'Actual only' },
          { value: 'volumetric-only', label: 'Volumetric only' },
        ],
      },
      {
        key: 'require-tracking-number',
        label: 'Require tracking number',
        type: 'boolean',
        default: true,
      },
      {
        key: 'auto-generate-tracking',
        label: 'Auto-generate tracking number',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    key: 'pre-alerts',
    label: 'Pre-alerts',
    optional: true,
    enabledByDefault: true,
    preferences: [
      {
        key: 'customer-can-create',
        label: 'Customer can create',
        type: 'boolean',
        default: true,
      },
      {
        key: 'require-invoice-upload',
        label: 'Require invoice upload',
        type: 'boolean',
        default: true,
        hint: 'Customs requires a supplier invoice.',
      },
      {
        key: 'require-declared-value',
        label: 'Require declared value',
        type: 'boolean',
        default: true,
      },
      {
        key: 'auto-match-on-tracking',
        label: 'Auto-match on tracking',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    key: 'warehouse',
    label: 'Warehouse',
    optional: false,
    enabledByDefault: true,
    preferences: [
      {
        key: 'auto-notify-on-receipt',
        label: 'Auto-notify on receipt',
        type: 'boolean',
        default: true,
      },
      {
        key: 'storage-free-days',
        label: 'Storage free days',
        type: 'integer',
        default: 30,
        min: 0,
        max: 365,
      },
      {
        key: 'storage-fee-per-day',
        label: 'Storage fee per day',
        type: 'decimal',
        default: '0.00',
        min: '0',
      },
    ],
  },
  {
    key: 'manifests',
    label: 'Manifests',
    optional: true,
    enabledByDefault: true,
    preferences: [
      {
        key: 'auto-number',
        label: 'Auto-number',
        type: 'boolean',
        default: true,
      },
      {
        key: 'number-prefix',
        label: 'Number prefix',
        type: 'string',
        default: 'MF-',
        maxLength: 10,
      },
    ],
  },
  {
    key: 'deliveries',
    label: 'Deliveries',
    optional: true,
    enabledByDefault: true,
    preferences: [
      {
        key: 'allow-branch-pickup',
        label: 'Allow branch pickup',
        type: 'boolean',
        default: true,
      },
      {
        key: 'allow-home-delivery',
        label: 'Allow home delivery',
        type: 'boolean',
        default: true,
      },
      {
        key: 'default-delivery-method',
        label: 'Default delivery method',
        type: 'enum',
        default: 'branch-pickup',
        options: [
          { value: 'branch-pickup', label: 'Branch pickup' },
          { value: 'home-delivery', label: 'Home delivery' },
        ],
      },
      {
        key: 'require-signature',
        label: 'Require signature',
        type: 'boolean',
        default: true,
      },
      {
        key: 'delivery-fee',
        label: 'Delivery fee',
        type: 'decimal',
        default: '0.00',
        min: '0',
      },
    ],
  },
  {
    key: 'invoices',
    label: 'Invoices',
    optional: false,
    enabledByDefault: true,
    preferences: [
      {
        key: 'auto-invoice-on-ready',
        label: 'Auto-invoice on ready',
        type: 'boolean',
        default: true,
      },
      {
        key: 'invoice-prefix',
        label: 'Invoice prefix',
        type: 'string',
        default: 'INV-',
        maxLength: 10,
      },
      {
        key: 'payment-terms-days',
        label: 'Payment terms days',
        type: 'integer',
        default: 0,
        min: 0,
        max: 180,
      },
      {
        key: 'tax-inclusive-pricing',
        label: 'Tax-inclusive pricing',
        type: 'boolean',
        default: false,
      },
      {
        key: 'gct-rate',
        label: 'GCT rate',
        type: 'decimal',
        default: '15.00',
        min: '0',
        max: '100',
        hint: 'Jamaica General Consumption Tax rate.',
      },
    ],
  },
  {
    key: 'payments',
    label: 'Payments',
    optional: false,
    enabledByDefault: true,
    preferences: [
      {
        key: 'allow-partial-payment',
        label: 'Allow partial payment',
        type: 'boolean',
        default: true,
      },
      {
        key: 'require-payment-before-release',
        label: 'Require payment before release',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    key: 'portal',
    label: 'Customer portal',
    optional: true,
    enabledByDefault: true,
    preferences: [
      {
        key: 'self-registration',
        label: 'Self-registration',
        type: 'boolean',
        default: true,
      },
      {
        key: 'require-email-verification',
        label: 'Require email verification',
        type: 'boolean',
        default: true,
      },
      {
        key: 'show-rates',
        label: 'Show rates',
        type: 'boolean',
        default: true,
      },
      {
        key: 'allow-pre-alert-create',
        label: 'Allow pre-alert creation',
        type: 'boolean',
        default: true,
      },
    ],
  },
] as const satisfies ModuleDefinition[])
