import Link from 'next/link'

/** Metadata-tier origin link for invoices generated by a recurring schedule. */
export function InvoiceOriginLink({
  profileId,
  profileName,
}: {
  profileId: string
  profileName: string
}) {
  return (
    <p className="text-muted-foreground text-sm">
      Generated from{' '}
      <Link
        href={`/recurring-invoices/${profileId}`}
        className="font-medium text-sky-600 hover:text-sky-700 hover:underline dark:text-sky-400 dark:hover:text-sky-300"
      >
        {profileName}
      </Link>
    </p>
  )
}
