"""Directory domain Pydantic contracts, grouped by sub-domain. Import surface

is unchanged: ``from domains.directory.schemas import BankResponse`` keeps
working — every schema is re-exported here.
"""

from .address import (
    DirectoryAddressCreate,
    DirectoryAddressResponse,
    DirectoryAddressUpdate,
)
from .education import (
    SecondarySchoolCreate,
    SecondarySchoolDeleteResponse,
    SecondarySchoolResponse,
    SecondarySchoolUpdate,
    UniversityCampusCreate,
    UniversityCampusDeleteResponse,
    UniversityCampusResponse,
    UniversityCampusUpdate,
    UniversityCreate,
    UniversityDeleteResponse,
    UniversityResponse,
    UniversityUpdate,
)
from .financial import (
    BankAccountCreate,
    BankAccountDeleteResponse,
    BankAccountResponse,
    BankAccountUpdate,
    BankBranchCreate,
    BankBranchDeleteResponse,
    BankBranchResponse,
    BankBranchUpdate,
    BankCreate,
    BankDeleteResponse,
    BankResponse,
    BankUpdate,
    CreditUnionBranchCreate,
    CreditUnionBranchDeleteResponse,
    CreditUnionBranchResponse,
    CreditUnionBranchUpdate,
    CreditUnionCreate,
    CreditUnionDeleteResponse,
    CreditUnionResponse,
    CreditUnionUpdate,
)
from .government import (
    MinistryCreate,
    MinistryDeleteResponse,
    MinistryDepartmentCreate,
    MinistryDepartmentDeleteResponse,
    MinistryDepartmentResponse,
    MinistryDepartmentUpdate,
    MinistryResponse,
    MinistryUpdate,
)

__all__ = [
    "BankAccountCreate",
    "BankAccountDeleteResponse",
    "BankAccountResponse",
    "BankAccountUpdate",
    "BankBranchCreate",
    "BankBranchDeleteResponse",
    "BankBranchResponse",
    "BankBranchUpdate",
    "BankCreate",
    "BankDeleteResponse",
    "BankResponse",
    "BankUpdate",
    "CreditUnionBranchCreate",
    "CreditUnionBranchDeleteResponse",
    "CreditUnionBranchResponse",
    "CreditUnionBranchUpdate",
    "CreditUnionCreate",
    "CreditUnionDeleteResponse",
    "CreditUnionResponse",
    "CreditUnionUpdate",
    "DirectoryAddressCreate",
    "DirectoryAddressResponse",
    "DirectoryAddressUpdate",
    "MinistryCreate",
    "MinistryDeleteResponse",
    "MinistryDepartmentCreate",
    "MinistryDepartmentDeleteResponse",
    "MinistryDepartmentResponse",
    "MinistryDepartmentUpdate",
    "MinistryResponse",
    "MinistryUpdate",
    "SecondarySchoolCreate",
    "SecondarySchoolDeleteResponse",
    "SecondarySchoolResponse",
    "SecondarySchoolUpdate",
    "UniversityCampusCreate",
    "UniversityCampusDeleteResponse",
    "UniversityCampusResponse",
    "UniversityCampusUpdate",
    "UniversityCreate",
    "UniversityDeleteResponse",
    "UniversityResponse",
    "UniversityUpdate",
]
