import { createPrefixedId } from '@876/core/id'

const entityPrefixes: Record<string, string> = {
  Tenant: 'ten',
  AppFinanceConnection: 'afc',
  Item: 'item',
  Customer: 'cus',
  Contact: 'con',
  Address: 'addr',
  Product: 'prod',
  Plan: 'plan',
  Price: 'prc',
  PriceTier: 'ptier',
  Addon: 'addon',
  PlanAddonAssociation: 'padd',
  PriceList: 'plist',
  PriceListEntry: 'plent',
  PriceListEntryTier: 'pltier',
  Quote: 'qt',
  QuoteLine: 'qtl',
  Invoice: 'inv',
  InvoiceLine: 'invl',
  Subscription: 'sub',
  SubscriptionItem: 'si',
  SubscriptionEvent: 'sev',
  SubscriptionAmendment: 'samd',
  SubscriptionAmendmentItem: 'sami',
  SubscriptionLifecycleSchedule: 'ssch',
  SubscriptionCharge: 'schg',
  SubscriptionNotificationOutbox: 'snot',
  SubscriptionCustomView: 'scv',
  SubscriptionCustomViewRule: 'scvr',
  SubscriptionCustomViewColumn: 'scvc',
  TaxAuthority: 'taxa',
  TaxRate: 'taxr',
  Role: 'role',
  Member: 'mem',
  Vendor: 'vend',
  Estimate: 'est',
  EstimateLine: 'estl',
  BankAccount: 'ba',
  BankTransaction: 'btxn',
  PaymentMode: 'pmode',
  Payment: 'pay',
  PaymentAllocation: 'palloc',
  CreditNote: 'cn',
  CreditNoteLine: 'cnl',
  CreditNoteAllocation: 'cnalloc',
  Refund: 'ref',
  PaymentTerm: 'pterm',
  Salesperson: 'salesp',
  Coupon: 'cpn',
  PromotionCode: 'promo',
  SubscriptionDiscount: 'sdisc',
  CouponCurrencyAmount: 'ccamt',
  CouponPlanApplicability: 'cpplan',
  CouponAddonApplicability: 'cpadd',
  CouponCustomerEligibility: 'cpelig',
  CouponRedemption: 'cpred',
  SubscriptionBillingRun: 'brun',
  PaymentProvider: 'pprov',
  PaymentProviderConnection: 'ppcon',
  AccountingProvider: 'aprov',
  AccountingProviderConnection: 'apcon',
  AccountingProviderSyncJob: 'apsync',
  ProviderReference: 'pref',
  PaymentAttempt: 'patm',
  PaymentProviderEvent: 'ppevt',
  PaymentMethod: 'pm',
  PaymentCredential: 'pcred',
  PaymentIntent: 'pi',
  CustomerLedgerEntry: 'cled',
  LateFeeAssessment: 'lfa',
}

export function generateId(prefix: string): string {
  return createPrefixedId(entityPrefixes[prefix] ?? prefix)
}
