import type { CrmCustomerRow } from '../_components/customers-table'

export const MOCK_CUSTOMERS: CrmCustomerRow[] = [
  {
    profileId: 'crm_cus_b4abf766e4ae472f9d0dd4bd9393b73c',
    billingCustomerId: 'cus_bm_001',
    name: 'Blue Mountain Coffee Exporters Ltd',
    legalName: 'Blue Mountain Coffee Exporters (Jamaica) Limited',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'orders@bluemountainexport.com',
    phone: '+18769260100',
    contactName: 'Marcus Sterling',
    contactEmail: 'marcus.sterling@bluemountainexport.com',
    contactPhone: '+18765550110',
    contactUserId: 'usr_msterling',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1718000000,
    updatedAt: 1723000000,
  },
  {
    profileId: 'crm_cus_klf_992',
    billingCustomerId: 'cus_klf_002',
    name: 'Kingston Logistics & Freight',
    legalName: 'Kingston Logistics Services Limited',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'dispatch@kingstonlogistics.com',
    phone: '+18769225500',
    contactName: 'Althea Morgan',
    contactEmail: 'althea@kingstonlogistics.com',
    contactPhone: '+18765550122',
    contactUserId: 'usr_amorgan',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1718500000,
    updatedAt: 1722000000,
  },
  {
    profileId: 'crm_cus_pth_881',
    billingCustomerId: 'cus_pth_003',
    name: 'Portmore Tech Hub & Co.',
    legalName: 'Portmore Technology Hub Inc.',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'hello@portmoretech.io',
    phone: '+18769882200',
    contactName: 'Devon Campbell',
    contactEmail: 'devon@portmoretech.io',
    contactPhone: '+18765550133',
    contactUserId: 'usr_dcampbell',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1719000000,
    updatedAt: 1722500000,
  },
  {
    profileId: 'crm_cus_sbr_774',
    billingCustomerId: 'cus_sbr_004',
    name: 'Sunburst Caribbean Resorts',
    legalName: 'Sunburst Hospitality Group Limited',
    isBusiness: true,
    typeLabel: 'External customer',
    email: 'concierge@sunburstresorts.com',
    phone: '+18769528000',
    contactName: 'Gabrielle Reid',
    contactEmail: 'gabrielle.reid@sunburstresorts.com',
    contactPhone: '+18765550144',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1719200000,
    updatedAt: 1723100000,
  },
  {
    profileId: 'crm_cus_ias_663',
    billingCustomerId: 'cus_ias_005',
    name: 'Island Agro Supplies Ltd',
    legalName: 'Island Agricultural Supplies & Distribution Ltd',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'sales@islandagro.com',
    phone: '+18769624000',
    contactName: 'Tariq Williams',
    contactEmail: 'tariq@islandagro.com',
    contactPhone: '+18765550155',
    contactUserId: 'usr_twilliams',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1719500000,
    updatedAt: 1723400000,
  },
  {
    profileId: 'crm_cus_zcs_552',
    billingCustomerId: 'cus_zcs_006',
    name: 'Zara Chin-Sue',
    legalName: null,
    isBusiness: false,
    typeLabel: '876 user',
    email: 'zara.chinsue@gmail.com',
    phone: '+18765550166',
    contactName: null,
    contactEmail: null,
    contactUserId: 'usr_zchinsue',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1720000000,
    updatedAt: 1723500000,
  },
  {
    profileId: 'crm_cus_twm_441',
    billingCustomerId: 'cus_twm_007',
    name: 'Tropical Wave Media Group',
    legalName: 'Tropical Wave Media Communications Ltd',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'press@tropicalwave.jm',
    phone: '+18769293100',
    contactName: 'Kareem Watson',
    contactEmail: 'kareem@tropicalwave.jm',
    contactPhone: '+18765550177',
    contactUserId: 'usr_kwatson',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1720500000,
    updatedAt: 1723600000,
  },
  {
    profileId: 'crm_cus_orh_330',
    billingCustomerId: 'cus_orh_008',
    name: 'Ocho Rios Hardware & Electrical',
    legalName: 'Ocho Rios Hardware Supplies Ltd',
    isBusiness: true,
    typeLabel: 'External customer',
    email: 'purchasing@ochorioshardware.com',
    phone: '+18769742400',
    contactName: 'Neville Brown',
    contactEmail: 'neville@ochorioshardware.com',
    contactPhone: '+18765550188',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1721000000,
    updatedAt: 1723700000,
  },
  {
    profileId: 'crm_cus_mr_229',
    billingCustomerId: 'cus_mr_009',
    name: 'Maya Rochester',
    legalName: null,
    isBusiness: false,
    typeLabel: '876 user',
    email: 'maya.rochester@outlook.com',
    phone: '+18765550199',
    contactName: null,
    contactEmail: null,
    contactUserId: 'usr_mrochester',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1721200000,
    updatedAt: 1723800000,
  },
  {
    profileId: 'crm_cus_mbf_118',
    billingCustomerId: 'cus_mbf_010',
    name: 'Montego Bay Financial Partners',
    legalName: 'Montego Bay Financial & Wealth Advisors Ltd',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'accounts@mobayfinance.com',
    phone: '+18769537000',
    contactName: 'Sharon Gordon',
    contactEmail: 'sharon.gordon@mobayfinance.com',
    contactPhone: '+18765550211',
    contactUserId: 'usr_sgordon',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1721500000,
    updatedAt: 1723900000,
  },
  {
    profileId: 'crm_cus_ds_907',
    billingCustomerId: 'cus_ds_011',
    name: 'Derrick Salmon',
    legalName: null,
    isBusiness: false,
    typeLabel: 'External customer',
    email: 'derrick.salmon@yahoo.com',
    phone: '+18765550222',
    contactName: null,
    contactEmail: null,
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1722000000,
    updatedAt: 1724000000,
  },
  {
    profileId: 'crm_cus_csd_896',
    billingCustomerId: 'cus_csd_012',
    name: 'Caribbean Solar Dynamics',
    legalName: 'Caribbean Renewable Solar Dynamics Ltd',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'support@solardynamics.jm',
    phone: '+18769068000',
    contactName: 'Andre Lewis',
    contactEmail: 'andre@solardynamics.jm',
    contactPhone: '+18765550233',
    contactUserId: 'usr_alewis',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1722500000,
    updatedAt: 1724100000,
  },
  {
    profileId: 'crm_cus_saa_785',
    billingCustomerId: 'cus_saa_013',
    name: 'St. Ann Auto Imports Ltd',
    legalName: 'St. Ann Auto Sales & Importation Ltd',
    isBusiness: true,
    typeLabel: 'External customer',
    email: 'inquiries@stannauto.com',
    phone: '+18769721500',
    contactName: 'Rohan Miller',
    contactEmail: 'rohan@stannauto.com',
    contactPhone: '+18765550244',
    ownerId: 'usr_admin',
    status: 'INACTIVE',
    createdAt: 1715000000,
    updatedAt: 1720000000,
  },
  {
    profileId: 'crm_cus_kt_674',
    billingCustomerId: 'cus_kt_014',
    name: 'Keisha Thompson',
    legalName: null,
    isBusiness: false,
    typeLabel: '876 user',
    email: 'keisha.t@gmail.com',
    phone: '+18765550255',
    contactName: null,
    contactEmail: null,
    contactUserId: 'usr_kthompson',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1723000000,
    updatedAt: 1724200000,
  },
  {
    profileId: 'crm_cus_bmt_563',
    billingCustomerId: 'cus_bmt_015',
    name: 'Bluefields Marine & Tackle',
    legalName: 'Bluefields Marine Services Ltd',
    isBusiness: true,
    typeLabel: 'External customer',
    email: 'harbor@bluefieldsmarine.com',
    phone: '+18769573300',
    contactName: 'Lancelot Clarke',
    contactEmail: 'lancelot@bluefieldsmarine.com',
    contactPhone: '+18765550266',
    ownerId: 'usr_admin',
    status: 'INACTIVE',
    createdAt: 1716000000,
    updatedAt: 1721000000,
  },
  {
    profileId: 'crm_cus_np_452',
    billingCustomerId: 'cus_np_016',
    name: 'Nadine Palmer',
    legalName: null,
    isBusiness: false,
    typeLabel: 'External customer',
    email: 'nadine.palmer@live.com',
    phone: '+18765550277',
    contactName: null,
    contactEmail: null,
    ownerId: 'usr_admin',
    status: 'INACTIVE',
    createdAt: 1717000000,
    updatedAt: 1721500000,
  },
  {
    profileId: 'crm_cus_dbe_341',
    billingCustomerId: 'cus_dbe_017',
    name: 'Discovery Bay Eco Tours',
    legalName: 'Discovery Bay Eco Adventures Ltd',
    isBusiness: true,
    typeLabel: '876 organization',
    email: 'bookings@discoveryecotours.com',
    phone: '+18769734200',
    contactName: 'Carlton Vassell',
    contactEmail: 'carlton@discoveryecotours.com',
    contactPhone: '+18765550288',
    contactUserId: 'usr_cvassell',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1723500000,
    updatedAt: 1724300000,
  },
  {
    profileId: 'crm_cus_cj_230',
    billingCustomerId: 'cus_cj_018',
    name: 'Camille Jackson',
    legalName: null,
    isBusiness: false,
    typeLabel: '876 user',
    email: 'c.jackson.jm@gmail.com',
    phone: '+18765550299',
    contactName: null,
    contactEmail: null,
    contactUserId: 'usr_cjackson',
    ownerId: 'usr_admin',
    status: 'ACTIVE',
    createdAt: 1724000000,
    updatedAt: 1724400000,
  },
]
