/**
 * `@876/admin` — privileged API client for 876 admin applications.
 *
 * This package is intentionally separate from `@876/sdk` so consumer apps do
 * not import or bundle admin endpoint paths.
 *
 * The `server-only` guard turns the convention "never import this from the
 * browser" into a build-time error: any Client Component that imports a runtime
 * value from this package will fail the build. Type-only imports are erased and
 * remain safe.
 *
 * @module @876/admin
 */
import 'server-only'

export { create876AdminClient } from './client'
export type { Admin876Client } from './client'
export { isDeleted, isDefault, isExpired, isRevoked } from './helpers'
export {
  AdminLookupError,
  isNotFoundError,
  unwrapOptional,
  unwrapResult,
} from './lookup'
export type { AdminError } from './lookup'
export type { AdminAuditEventCreateParams } from './resources/audit-events'
export type {
  AdminJsonValue,
  AdminOnboardingAnswersReplaceParams,
  AdminOnboardingCatalog,
  AdminOnboardingField,
  AdminOnboardingFieldType,
  AdminOnboardingOption,
  AdminOnboardingSection,
  AdminOnboardingSession,
  AdminOnboardingTargetType,
  AdminOnboardingValidation,
  AdminOnboardingValidationIssue,
} from './resources/onboarding'
export type {
  Admin876ClientOptions,
  AdminAccount,
  AdminAuditEvent,
  AdminBillingAccount,
  AdminBillingAccountCreateParams,
  AdminBillingAccountUpdateParams,
  AdminDeletedBillingAccount,
  AdminUser,
  AdminUsernameAvailability,
  AdminConsumerContact,
  AdminConsumerContactCreateParams,
  AdminConsumerContactUpdateParams,
  AdminConsumerProfile,
  AdminConsumerProfileUpdateParams,
  AdminDeletedConsumerContact,
  AdminDeletedConsumerProfile,
  AdminUserCreateParams,
  AdminUserUpdateParams,
  AdminDeletedUser,
  AdminOrganization,
  AdminOrganizationCreateParams,
  AdminOrganizationUpdateParams,
  AdminOrgSetupParams,
  AdminDeletedOrganization,
  AdminInviteToken,
  AdminInviteCreateParams,
  AdminMembership,
  AdminMembershipCreateParams,
  AdminMembershipUpdateParams,
  AdminDeletedMembership,
  AdminApp,
  AdminAppKind,
  AdminAppStatus,
  AdminAppPublic,
  AdminAppCreated,
  AdminAppCreateParams,
  AdminAppUpdateParams,
  AdminDeletedApp,
  AdminProvisioningTargetType,
  AdminProvisioningValueType,
  AdminProvisioningProperty,
  AdminProvisioningResource,
  AdminProvisioningStep,
  AdminProvisioningManifestRevision,
  AdminProvisioningManifest,
  AdminProvisioningDraftReplaceParams,
  AdminProvisioningValidation,
  AdminProvisioningCatalog,
  AdminProvisioningNote,
  AdminProvisioningRun,
  AdminProvisioningRunStatus,
  AdminProvisioningReconciliationResult,
  AdminDeletedProvisioningNote,
  AdminApiKey,
  AdminApiKeyCreated,
  AdminApiKeyCreateParams,
  AdminApiKeyUpdateParams,
  AdminDeletedApiKey,
  AdminRoutingMembership,
  AdminUserFeature,
  AdminOAuthGrant,
  AdminUserApp,
  AdminListResponse,
  AdminSearchResponse,
  AdminResult,
  AdminAddress,
  AdminAddressCreateParams,
  AdminAddressUpdateParams,
  AdminDeletedAddress,
  AdminFeature,
  AdminFeatureCreateParams,
  AdminFeatureEvaluateParams,
  AdminFeatureSearchParams,
  AdminFeatureUpdateParams,
  AdminDeletedFeature,
  AdminOrgFeature,
  AdminOrgFeatureGrantParams,
  AdminOrgFeatureUpdateParams,
  AdminDeletedOrgFeature,
  AdminUserFeatureGrantParams,
  AdminUserFeatureUpdateParams,
  AdminDeletedUserFeature,
  ReservedUsername,
  ReservedUsernameCreateParams,
  DeletedReservedUsername,
  UnlinkedAccount,
  SessionRevoke,
  AdminSubscription,
  AdminSubscriptionBatch,
  AdminSubscriptionStatus,
  AdminSubscriptionItem,
  AdminSubscriptionItemCreateParams,
  AdminSubscriptionItemUpdateParams,
  AdminDeletedSubscriptionItem,
  AdminSubscriptionCreateParams,
  AdminSubscriptionUpdateParams,
  AdminDeletedSubscription,
  AdminProduct,
  AdminProductCreateParams,
  AdminProductModulesReplaceParams,
  AdminProductUpdateParams,
  AdminDeletedProduct,
  AdminApplicationModule,
  AdminApplicationModuleCreateParams,
  AdminApplicationModuleUpdateParams,
  AdminDeletedApplicationModule,
  AdminPrice,
  AdminPriceCreateParams,
  AdminPriceUpdateParams,
  AdminOrgRole,
  AdminOrgRoleCreateParams,
  AdminOrgRoleUpdateParams,
  AdminOrgContact,
  AdminOrgContactCreateParams,
  AdminOrgContactUpdateParams,
  AdminDeletedOrgContact,
  AdminOrgLocation,
  AdminOrgLocationCreateParams,
  AdminOrgLocationUpdateParams,
  AdminDeletedOrgLocation,
  AdminOrgDepartment,
  AdminOrgDepartmentCreateParams,
  AdminOrgDepartmentUpdateParams,
  AdminDeletedOrgDepartment,
  AdminEmployeeProfile,
  AdminEmployeeProfileCreateParams,
  AdminEmployeeProfileUpdateParams,
  AdminDeletedEmployeeProfile,
  AdminOrgMember,
  AdminAppAssignment,
  AdminAppAssignmentCreateParams,
} from './types'
