import { billingIntegration } from '@/lib/876'
import type { AdminSubscription } from '@876/admin'
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from '@876/ui/empty'
import { ReceiptText } from '@876/ui/icons'
import { Skeleton } from '@876/ui/skeleton'

import { formatDate, formatMoney, statusBadgeClass } from '@/lib/format'
import { cn } from '@876/core/utils'

type InvoiceRow = {
  id: string
  number?: string
  status?: string
  currency?: string
  subscriptionId?: string | null
  totalAmount?: string | number
  amountDue?: string | number
  issueAt?: number | null
  paidAt?: number | null
  createdAt?: number
}

function invoiceStatusClass(status: string): string {
  switch (status.toLowerCase()) {
    case 'paid':
      return statusBadgeClass('active')
    case 'open':
    case 'sent':
    case 'partially_paid':
      return statusBadgeClass('trialing')
    case 'overdue':
      return statusBadgeClass('past_due')
    case 'void':
    case 'uncollectible':
      return statusBadgeClass('canceled')
    default:
      return statusBadgeClass('draft')
  }
}

function InvoiceRowItem({ invoice }: { invoice: InvoiceRow }) {
  const label = invoice.number || invoice.id

  return (
    <li className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0">
      <div className="min-w-0">
        <p className="truncate text-[0.8125rem] font-medium">{label}</p>
        <p className="text-muted-foreground mt-0.5 text-xs">
          Issued {invoice.issueAt ? formatDate(invoice.issueAt) : '—'}
        </p>
      </div>
      <div className="flex shrink-0 items-center gap-2.5">
        <span className="text-[0.8125rem] font-medium tabular-nums">
          {formatMoney(invoice.totalAmount, invoice.currency)}
        </span>
        {invoice.status && (
          <span
            className={cn(
              'inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium',
              invoiceStatusClass(invoice.status)
            )}
          >
            {invoice.status.toLowerCase().replace(/_/g, ' ')}
          </span>
        )}
      </div>
    </li>
  )
}

/**
 * Streams the Billing invoices generated by this subscription. Invoices are
 * listed per organization, so the subscription's share is filtered here.
 */
export async function SubscriptionTransactions({
  organizationId,
  subscription,
}: {
  organizationId: string
  subscription: AdminSubscription
}) {
  const result = await billingIntegration.invoices.list(organizationId)
  if (result.error) throw new Error(result.error.message)

  const invoices = ((result.data?.data ?? []) as InvoiceRow[]).filter(
    (invoice) => invoice.id && invoice.subscriptionId === subscription.id
  )

  if (invoices.length === 0)
    return (
      <Empty className="border-0">
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <ReceiptText aria-hidden="true" />
          </EmptyMedia>
          <EmptyTitle>No transactions yet</EmptyTitle>
          <EmptyDescription>
            Invoices and charges for this subscription will appear here.
          </EmptyDescription>
        </EmptyHeader>
      </Empty>
    )

  return (
    <ul className="divide-876-surface-border divide-y">
      {invoices.map((invoice) => (
        <InvoiceRowItem key={invoice.id} invoice={invoice} />
      ))}
    </ul>
  )
}

export function SubscriptionTransactionsFallback() {
  return (
    <div className="space-y-3 py-1" aria-label="Loading transactions">
      <Skeleton className="h-10 w-4/5" />
      <Skeleton className="h-10 w-3/5" />
      <Skeleton className="h-10 w-2/3" />
    </div>
  )
}
