import {
  create876Client as createPlatformClient,
  type ClientOptions as PlatformClientOptions,
} from '@876/sdk'
import { browserCollections, browserNotes } from '@876/widgets/browser'
import type { AppId } from './context/types.ts'

export interface ClientOptions extends PlatformClientOptions {
  app?: AppId
}

export function create876Client({
  app: _app,
  ...platformOptions
}: ClientOptions = {}) {
  const platform = createPlatformClient(platformOptions)

  return {
    auth: platform.auth,
    sessions: {
      me: {
        retrieve: platform.auth.getSession,
        list: platform.auth.me.listSessions,
        revoke: platform.auth.me.revokeSession,
      },
    },
    oauth: platform.oauth,
    auditEvents: platform.auditEvents,
    users: { me: platform.users },
    organizations: platform.organizations,
    memberships: platform.memberships,
    apps: platform.apps,
    features: platform.features,
    entitlements: platform.subscriptions,
    locations: platform.locations,
    contacts: platform.contacts,
    departments: platform.departments,
    employees: platform.employees,
    roles: platform.roles,
    organizationMembers: platform.organizationMembers,
    appAssignments: platform.appAssignments,
    invites: platform.invites,
    mobileNumbers: platform.mobileNumbers,
    mobileNumberVerifications: platform.mobileNumberVerifications,
    permissions: platform.permissions,
    notes: browserNotes,
    collections: browserCollections,
  }
}

export type Client876 = ReturnType<typeof create876Client>
export type { PlatformClientOptions }
export type {
  Customer as CrmCustomer,
  CreateCustomerInput as CrmCustomerCreateInput,
  CustomerList as CrmCustomerList,
  CustomerProfile as CrmCustomerProfile,
  CustomerProfileStatus as CrmCustomerProfileStatus,
  UpdateCustomerInput as CrmCustomerUpdateInput,
  CrmRequest,
  CreateRequestInput as CrmRequestCreateInput,
  ListRequestsQuery as CrmListRequestsQuery,
  RequestList as CrmRequestList,
  UpdateRequestInput as CrmRequestUpdateInput,
  RequestCategory as CrmRequestCategory,
  CreateRequestCategoryInput as CrmRequestCategoryCreateInput,
  DeleteRequestCategoryInput as CrmRequestCategoryDeleteInput,
  RequestCategoryList as CrmRequestCategoryList,
  UpdateRequestCategoryInput as CrmRequestCategoryUpdateInput,
  RequestPriority as CrmRequestPriority,
  CreateRequestPriorityInput as CrmRequestPriorityCreateInput,
  DeleteRequestPriorityInput as CrmRequestPriorityDeleteInput,
  ListRequestPrioritiesQuery as CrmListRequestPrioritiesQuery,
  RequestPriorityList as CrmRequestPriorityList,
  UpdateRequestPriorityInput as CrmRequestPriorityUpdateInput,
  RequestForm as CrmRequestForm,
  CreateRequestFormInput as CrmRequestFormCreateInput,
  ListFormCustomerRequestsQuery as CrmListFormCustomerRequestsQuery,
  ListRequestFormsQuery as CrmListRequestFormsQuery,
  RequestFormDefinition as CrmRequestFormDefinition,
  RequestFormField as CrmRequestFormField,
  RequestFormFieldMapping as CrmRequestFormFieldMapping,
  RequestFormList as CrmRequestFormList,
  RequestFormStatus as CrmRequestFormStatus,
  RequestFormSubmission as CrmRequestFormSubmission,
  RequestFormSubmissionList as CrmRequestFormSubmissionList,
  RequestFormSubmissionRecord as CrmRequestFormSubmissionRecord,
  SubmitRequestFormInput as CrmRequestFormSubmitInput,
  UpdateRequestFormInput as CrmRequestFormUpdateInput,
  CrmRequestNote,
  CreateRequestNoteInput as CrmRequestNoteCreateInput,
  DeleteRequestNoteInput as CrmRequestNoteDeleteInput,
  RequestNoteList as CrmRequestNoteList,
  ListRequestNotesInput as CrmListRequestNotesInput,
  RequestNoteVisibility as CrmRequestNoteVisibility,
  UpdateRequestNoteInput as CrmRequestNoteUpdateInput,
  RequestReminder as CrmRequestReminder,
  CreateRequestReminderInput as CrmRequestReminderCreateInput,
  DeleteNestedRequestInput as CrmRequestReminderDeleteInput,
  RequestReminderList as CrmRequestReminderList,
  UpdateRequestReminderInput as CrmRequestReminderUpdateInput,
  RequestTask as CrmRequestTask,
  CreateRequestTaskInput as CrmRequestTaskCreateInput,
  DeleteNestedRequestInput as CrmRequestTaskDeleteInput,
  RequestTaskList as CrmRequestTaskList,
  UpdateRequestTaskInput as CrmRequestTaskUpdateInput,
  RequestEvent as CrmRequestEvent,
  RequestEventList as CrmRequestEventList,
  RequestEventParticipant as CrmRequestEventParticipant,
  CreateRequestEventInput as CrmRequestEventCreateInput,
  UpdateRequestEventInput as CrmRequestEventUpdateInput,
  CreateRequestEventParticipantInput as CrmRequestEventParticipantCreateInput,
  UpdateRequestEventParticipantInput as CrmRequestEventParticipantUpdateInput,
  RequestEventStatus as CrmRequestEventStatus,
  RequestEventBusyStatus as CrmRequestEventBusyStatus,
  RequestSubcategory as CrmRequestSubcategory,
  CreateRequestSubcategoryInput as CrmRequestSubcategoryCreateInput,
  DeleteRequestCategoryInput as CrmRequestSubcategoryDeleteInput,
  UpdateRequestSubcategoryInput as CrmRequestSubcategoryUpdateInput,
  ReminderStatus as CrmReminderStatus,
  TaskStatus as CrmTaskStatus,
  Team as CrmTeam,
  TeamAutoAssign as CrmTeamAutoAssign,
  CreateTeamInput as CrmTeamCreateInput,
  DeleteTeamInput as CrmTeamDeleteInput,
  TeamList as CrmTeamList,
  ListTeamsQuery as CrmListTeamsQuery,
  TeamMember as CrmTeamMember,
  AddTeamMemberInput as CrmTeamMemberAddInput,
  TeamMemberList as CrmTeamMemberList,
  TeamMemberRole as CrmTeamMemberRole,
  UpdateTeamMemberInput as CrmTeamMemberUpdateInput,
  TeamStatus as CrmTeamStatus,
  UpdateTeamInput as CrmTeamUpdateInput,
  RequestNoteKind,
  RequestPriority,
  RequestChannel,
  RequestStatus,
} from '@876/crm'
