import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { format } from 'prettier'

type JsonObject = Record<string, unknown>

const HTTP_METHODS = new Set([
  'delete',
  'get',
  'head',
  'options',
  'patch',
  'post',
  'put',
])
const OPERATION_METADATA_FIELDS = [
  'operationId',
  'summary',
  'description',
  'tags',
] as const
const contractPath = fileURLToPath(
  new URL('../../billing/contracts/v1/openapi.json', import.meta.url)
)
const outputPath = fileURLToPath(
  new URL('../src/http/openapi/v1-contract.generated.ts', import.meta.url)
)

function operationMetadata(document: JsonObject): JsonObject {
  const result: JsonObject = {}
  const paths = document.paths as JsonObject

  for (const [path, pathItemValue] of Object.entries(paths)) {
    const pathItem = pathItemValue as JsonObject
    for (const [method, operationValue] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method)) continue

      const operation = operationValue as JsonObject
      const metadata: JsonObject = {}
      for (const field of OPERATION_METADATA_FIELDS) {
        if (Object.hasOwn(operation, field)) metadata[field] = operation[field]
      }
      result[`${method.toUpperCase()} ${path}`] = metadata
    }
  }

  return result
}

function operationContracts(document: JsonObject): JsonObject {
  const result: JsonObject = {}
  const paths = document.paths as JsonObject

  for (const [path, pathItemValue] of Object.entries(paths)) {
    const pathItem = pathItemValue as JsonObject
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method)) continue
      result[`${method.toUpperCase()} ${path}`] = operation
    }
  }

  return result
}

async function render(document: JsonObject): Promise<string> {
  const components = document.components as JsonObject | undefined
  const schemas = (components?.schemas as JsonObject | undefined) ?? {}
  const metadata = operationMetadata(document)
  const contracts = operationContracts(document)

  const source = `// Generated from apps/billing/contracts/v1/openapi.json.
// Run \`pnpm --filter @876/billing-api api:contract:manifest:generate\` to update.
// Do not edit this file by hand.

export const v1OperationMetadata = ${JSON.stringify(metadata, null, 2)} as const

export const v1OperationContracts = ${JSON.stringify(contracts, null, 2)} as const

export const v1ComponentSchemas = ${JSON.stringify(schemas, null, 2)} as const
`
  return format(source, {
    parser: 'typescript',
    semi: false,
    singleQuote: true,
    trailingComma: 'es5',
  })
}

async function main(): Promise<void> {
  const contract = JSON.parse(
    await readFile(contractPath, 'utf8')
  ) as JsonObject
  const generated = await render(contract)

  if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '')
    if (current !== generated) {
      console.error(
        'Billing v1 compatibility manifest is stale. Run api:contract:manifest:generate.'
      )
      process.exitCode = 1
    }
    return
  }

  await writeFile(outputPath, generated, 'utf8')
  console.log('Generated Billing v1 compatibility manifest.')
}

void main()
