#!/usr/bin/env python3
"""Generate the FastAPI route registry from the frozen Phase 1 contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

BILLING_API_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = BILLING_API_ROOT.parents[1]
MANIFEST_PATH = REPOSITORY_ROOT / "apps" / "billing" / "contracts" / "v1" / "route-manifest.json"
OUTPUT_PATH = BILLING_API_ROOT / "domains" / "billing" / "generated_routes.py"


def render() -> str:
    manifest: dict[str, Any] = json.loads(MANIFEST_PATH.read_text())
    lines = [
        "# Generated by scripts/generate_routes.py; do not edit manually.",
        "from domains.billing.contracts import RouteSpec",
        "",
        "ROUTES: tuple[RouteSpec, ...] = (",
    ]
    for route in manifest["routes"]:
        for operation in route["operations"]:
            permissions = operation.get("declared_permissions") or []
            scopes = operation.get("declared_scopes") or []
            lines.append(
                "    RouteSpec("
                f"path={route['path']!r}, method={operation['method']!r}, "
                f"auth_tier={operation['auth_tier']!r}, "
                f"permission={(permissions[0] if permissions else None)!r}, "
                f"scope={(scopes[0] if scopes else None)!r}, source={route['source']!r}),"
            )
    lines.extend((")", ""))
    return "\n".join(lines)


def generate() -> int:
    OUTPUT_PATH.write_text(render())
    print(f"Generated {OUTPUT_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


def check() -> int:
    if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text() != render():
        print("Billing FastAPI route registry is stale.", file=sys.stderr)
        print("Run: pnpm --filter @876/billing-api api:routes:generate", file=sys.stderr)
        return 1
    print("Billing FastAPI route registry matches the frozen v1 contract")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "check"))
    args = parser.parse_args()
    return generate() if args.command == "generate" else check()


if __name__ == "__main__":
    raise SystemExit(main())
