export const AnalyticsEvent = {
  AuthLoginSubmitted: 'auth_login_submitted',
  AuthLoginSuccess: 'auth_login_success',
  AuthLoginFailed: 'auth_login_failed',
  AuthRegisterSubmitted: 'auth_register_submitted',
  AuthRegisterSuccess: 'auth_register_success',
  AuthRegisterFailed: 'auth_register_failed',
  AuthSocialLoginSubmitted: 'auth_social_login_submitted',
  AuthSocialLoginSuccess: 'auth_social_login_success',
  AuthSocialLoginFailed: 'auth_social_login_failed',
  AuthLogoutClicked: 'auth_logout_clicked',
  AuthLogoutSucceeded: 'auth_logout_succeeded',
  AuthMagicOtpSent: 'auth_magic_otp_sent',
  AuthMagicOtpFailed: 'auth_magic_otp_failed',
  AuthMagicOtpVerified: 'auth_magic_otp_verified',
  AuthPasswordResetRequested: 'auth_password_reset_requested',
  AuthPasswordResetCompleted: 'auth_password_reset_completed',
  AuthPasswordResetFailed: 'auth_password_reset_failed',
  AuthEmailVerificationStarted: 'auth_email_verification_started',
  AuthEmailVerificationCompleted: 'auth_email_verification_completed',
  AuthEmailVerificationFailed: 'auth_email_verification_failed',
  AuthEmailVerificationResent: 'auth_email_verification_resent',
  AuthFormAbandoned: 'auth_form_abandoned',
  SessionStarted: 'session_started',
  SessionResumed: 'session_resumed',
  SessionEnded: 'session_ended',
  PageViewed: '$pageview',
  PageViewedDetailed: 'page_viewed',
  UnhandledException: 'error_unhandled_exception',
  UnhandledRejection: 'error_unhandled_rejection',
  ApiError: 'api_error',
  NetworkRequestFailed: 'network_request_failed',
} as const

export type AnalyticsEventName =
  (typeof AnalyticsEvent)[keyof typeof AnalyticsEvent]
