import Link from 'next/link'

/** Metadata-tier origin link for invoices generated by a recurring schedule. */
export function InvoiceOriginLink({
  profileId,
  profileName,
}: {
  profileId: string
  profileName: string
}) {
  return (
    <p className="mt-1 text-sm">
      Generated from{' '}
      <Link
        href={`/recurring-invoices/${profileId}`}
        className="underline underline-offset-2"
      >
        {profileName}
      </Link>
    </p>
  )
}
