/**
 * Mirrors the dev secrets the consumer app needs into
 * `apps/876/.env.development.local` on devcontainer start.
 *
 * Forwarded-port URLs and CORS origins are **not** handled here — those are
 * provider-agnostic and live in `scripts/setup-dev-env.mjs`, which runs for
 * both Codespaces and Ona/Gitpod as part of `pnpm dev`.
 *
 * Runs automatically on postStartCommand in devcontainer.json.
 */
import { randomBytes } from 'node:crypto'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { mergeEnvFile, readEnvValue } from '../scripts/env-file.mjs'

const root = join(fileURLToPath(import.meta.url), '..', '..')
const appLocalPath = join(root, 'apps', '876', '.env.development.local')

// Reuse an existing dev cookie password if one was already generated, so the
// session cookie survives container rebuilds; otherwise mint a new one.
const cookiePassword =
  readEnvValue(appLocalPath, 'WORKOS_COOKIE_PASSWORD') ??
  randomBytes(24).toString('hex')

// The internal key is a shared dev secret; mirror it from apps/api so the
// consumer app's server-side admin-client calls (session bootstrap) authorize.
const internalKey =
  readEnvValue(join(root, 'apps', 'api', '.env'), 'API_INTERNAL_KEY') ?? ''

mergeEnvFile(
  appLocalPath,
  {
    // Server-to-server API calls stay on loopback (same machine).
    API_URL: 'http://localhost:4000',
    // Seals the AuthKit session cookie (consumer app only, >= 32 chars).
    WORKOS_COOKIE_PASSWORD: cookiePassword,
    // Shared secret for server-to-server (admin-client) calls — matches apps/api.
    API_INTERNAL_KEY: internalKey,
  },
  '# Auto-generated by .devcontainer/setup-env.mjs — do not commit.'
)

console.log('[setup-env] Wrote apps/876/.env.development.local')
