/**
 * Writes .env.development.local files in apps/876 and apps/api with
 * Codespaces-specific URLs so the apps can reach each other and the API
 * can accept requests from the forwarded port origins.
 *
 * Runs automatically on postStartCommand in devcontainer.json.
 * Safe to run locally — exits without writing if CODESPACE_NAME is unset.
 */
import { writeFileSync, existsSync, readFileSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(import.meta.url), '..', '..')
const space = process.env.CODESPACE_NAME
const domain = process.env.GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN

if (!space || !domain) {
  console.log('[setup-env] Not in a Codespace — skipping env setup.')
  process.exit(0)
}

// Reuse an existing dev cookie password if one was already generated, so the
// session cookie survives Codespace rebuilds; otherwise mint a new one.
const appLocalPath = join(root, 'apps', '876', '.env.development.local')
const existingAppEnv = existsSync(appLocalPath)
  ? readFileSync(appLocalPath, 'utf8')
  : ''
const existingCookiePassword = existingAppEnv.match(
  /^WORKOS_COOKIE_PASSWORD=(.+)$/m
)?.[1]
const cookiePassword = existingCookiePassword || randomBytes(24).toString('hex')

// Preserve a previously-provisioned consumer app API key across rebuilds — it
// maps to a hashed row in the API's api_keys table and cannot be regenerated
// here (no DB access). The consumer auth bridge requires it (X-876-API-Key);
// without it every /auth/* call is rejected with api-key/missing.
const existingApiKey = existingAppEnv.match(/^API_876_KEY=(.+)$/m)?.[1] ?? ''

// The internal key is a shared dev secret; mirror it from apps/api so the
// consumer app's server-side admin-client calls (session bootstrap) authorize.
const apiEnvPath = join(root, 'apps', 'api', '.env')
const internalKey =
  (existsSync(apiEnvPath)
    ? readFileSync(apiEnvPath, 'utf8').match(/^API_INTERNAL_KEY=(.+)$/m)?.[1]
    : undefined) ?? ''

const appUrl = `https://${space}-3000.${domain}`
const adminUrl = `https://${space}-3002.${domain}`
const apiUrl = `https://${space}-4000.${domain}`

// apps/876 — overrides for the app's NEXT_PUBLIC vars
const appEnv = [
  `# Auto-generated by .devcontainer/setup-env.mjs — do not commit`,
  `NEXT_PUBLIC_APP_URL=${appUrl}`,
  `NEXT_PUBLIC_ADMIN_URL=${adminUrl}`,
  `# Server-to-server API calls stay on localhost (same machine):`,
  `API_URL=http://localhost:4000`,
  `# Seals the AuthKit session cookie (consumer app only, >= 32 chars):`,
  `WORKOS_COOKIE_PASSWORD=${cookiePassword}`,
  `# App API key (876-consumer slug) — auth bridge attaches it as X-876-API-Key.`,
  `API_876_KEY=${existingApiKey}`,
  `# Shared secret for server-to-server (admin-client) calls — matches apps/api.`,
  `API_INTERNAL_KEY=${internalKey}`,
  ``,
].join('\n')

writeFileSync(join(root, 'apps', '876', '.env.development.local'), appEnv)
console.log(`[setup-env] Wrote apps/876/.env.development.local`)

// apps/api — CORS_ALLOWED_ORIGINS override (env.ts also auto-detects via
// CODESPACE_NAME, but this makes it explicit for debugging)
const corsOrigins = `http://localhost:3000,http://localhost:3002,${appUrl},${adminUrl}`
const apiEnv = [
  `# Auto-generated by .devcontainer/setup-env.mjs — do not commit`,
  `CORS_ALLOWED_ORIGINS=${corsOrigins}`,
  ``,
].join('\n')

writeFileSync(join(root, 'apps', 'api', '.env.development.local'), apiEnv)
console.log(`[setup-env] Wrote apps/api/.env.development.local`)
console.log(`[setup-env] App:   ${appUrl}`)
console.log(`[setup-env] Admin: ${adminUrl}`)
console.log(`[setup-env] API:   ${apiUrl}`)
