import Link from 'next/link'

export type BillingAccountSummary = {
  id: string
  name: string | null
  email: string | null
  currency: string | null
  taxExempt: string | null
  balance: number
  defaultPaymentMethodId: string | null
}

export type PaymentMethodSummary = {
  id: string
  displayLabel: string | null
  isDefault: boolean
  card: unknown
  expMonth: number | null
  expYear: number | null
}

export type SubscriptionBillingSummaryProps = {
  account: BillingAccountSummary | null
  paymentMethods: PaymentMethodSummary[]
  subscriptionPaymentMethodId: string | null
  latestInvoiceId: string | null
  invoiceHref?: string
}

function cardDetail(method: PaymentMethodSummary): string {
  const card = method.card
  const record =
    card && typeof card === 'object' ? (card as Record<string, unknown>) : null
  const brand = typeof record?.brand === 'string' ? record.brand : null
  const last4 =
    typeof record?.last4 === 'string' && /^\d{4}$/.test(record.last4)
      ? record.last4
      : null
  // Display labels are normally generated by Billing, but never trust one to
  // render a PAN if a provider payload is mis-serialized upstream.
  const displayLabel =
    method.displayLabel && !/\d(?:[ -]?\d){11,18}/.test(method.displayLabel)
      ? method.displayLabel
      : null
  const label =
    displayLabel ?? [brand, last4 && `•••• ${last4}`].filter(Boolean).join(' ')
  const expiry =
    method.expMonth && method.expYear
      ? ` · ${String(method.expMonth).padStart(2, '0')}/${method.expYear}`
      : ''
  return `${label || 'Payment method'}${expiry}`
}

function Row({
  label,
  children,
  mono = false,
}: {
  label: string
  children: React.ReactNode
  mono?: boolean
}) {
  return (
    <div className="flex items-baseline justify-between gap-4 py-2 first:pt-0 last:pb-0">
      <dt className="text-muted-foreground shrink-0 text-[0.8125rem]">
        {label}
      </dt>
      <dd
        className={
          mono
            ? 'text-muted-foreground min-w-0 truncate text-right font-mono text-xs'
            : 'min-w-0 truncate text-right text-[0.8125rem]'
        }
      >
        {children}
      </dd>
    </div>
  )
}

/** Presentational billing-account summary shared by subscription detail views. */
export function SubscriptionBillingSummary({
  account,
  paymentMethods,
  subscriptionPaymentMethodId,
  latestInvoiceId,
  invoiceHref,
}: SubscriptionBillingSummaryProps) {
  if (!account)
    return (
      <dl className="divide-876-surface-border divide-y">
        <Row label="Billing account">Not set up</Row>
      </dl>
    )

  const selectedId =
    subscriptionPaymentMethodId ?? account.defaultPaymentMethodId
  const selected = paymentMethods.find((method) => method.id === selectedId)
  const source = subscriptionPaymentMethodId
    ? 'Subscription payment method'
    : 'Billing account default'
  const otherMethods = paymentMethods
    .filter((method) => method.id !== selectedId)
    .slice(0, 5)

  return (
    <div className="space-y-4">
      <dl className="divide-876-surface-border divide-y">
        <Row label="Billing account (payer)">
          {account.name || account.email || 'Unnamed billing account'}
        </Row>
        <Row label="Currency">{account.currency ?? '—'}</Row>
        <Row label="Tax status">{account.taxExempt ?? '—'}</Row>
        <Row label="Balance">
          {account.currency
            ? `${account.currency} ${account.balance}`
            : String(account.balance)}
        </Row>
        <Row label="Account ID" mono>
          {account.id}
        </Row>
        <Row label={source}>{selected ? cardDetail(selected) : 'None'}</Row>
        {latestInvoiceId && (
          <Row label="Latest invoice" mono>
            {invoiceHref ? (
              <Link
                href={invoiceHref}
                className="text-sky-600 hover:underline dark:text-sky-400"
              >
                {latestInvoiceId}
              </Link>
            ) : (
              latestInvoiceId
            )}
          </Row>
        )}
      </dl>

      {otherMethods.length > 0 && (
        <div>
          <div className="text-muted-foreground text-[0.6875rem] tracking-wide uppercase">
            Other payment methods
          </div>
          <ul className="divide-876-surface-border mt-2 divide-y">
            {otherMethods.map((method) => (
              <li
                key={method.id}
                className="flex items-center justify-between gap-3 py-2 text-[0.8125rem] first:pt-0 last:pb-0"
              >
                <span className="min-w-0 truncate">{cardDetail(method)}</span>
                {method.isDefault && (
                  <span className="border-border bg-muted/40 text-muted-foreground shrink-0 rounded-md border px-2 py-0.5 text-xs font-medium">
                    Default
                  </span>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

export function SubscriptionBillingSummaryFallback() {
  return (
    <div className="space-y-2" aria-label="Loading billing details">
      <div className="bg-muted h-4 w-4/5 animate-pulse rounded" />
      <div className="bg-muted h-4 w-3/5 animate-pulse rounded" />
      <div className="bg-muted h-4 w-2/3 animate-pulse rounded" />
    </div>
  )
}
