export type {
  CrmCustomer,
  CrmCustomerList,
  CrmCustomerProfile,
  CrmCustomerProfileStatus,
  CrmCustomerCreateInput,
  CrmCustomerUpdateInput,
  CrmRequest,
  CrmRequestList,
  RequestStatus,
  RequestPriority,
  RequestCategory,
  RequestSource,
  CrmRequestCreateInput,
  CrmRequestUpdateInput,
  CrmRequestNote,
  CrmRequestNoteList,
  CrmRequestNoteCreateInput,
  CrmRequestNoteUpdateInput,
  RequestNoteKind,
  CrmRequestNoteDeleteInput,
} from '@876/client'
