export type {
  CrmCustomer,
  CrmCustomerList,
  CrmCustomerProfile,
  CrmCustomerProfileStatus,
  CrmCustomerCreateInput,
  CrmCustomerUpdateInput,
  CrmRequest,
  CrmRequestList,
  RequestStatus,
  RequestPriority,
  RequestCategory,
  RequestSource,
  CrmRequestCreateInput,
  CrmRequestUpdateInput,
} from '@876/client'
