/**
 * Points every app's browser-visible dev URLs at the current workspace's
 * forwarded origins.
 *
 * On a plain local machine `http://localhost:<port>` is reachable from the
 * browser, so the committed `.env.development` defaults are correct and this
 * script exits without writing. Inside a remote workspace the browser is on a
 * different machine, so each app's public URLs
 * must be the forwarded HTTPS origins instead — otherwise cross-app links,
 * browser-side SDK calls, OAuth redirects, and the API's CORS allow-list all
 * point at a localhost that only exists inside the container.
 *
 * Values land in each app's `.env.development.local` (gitignored, highest
 * precedence in Next.js). Existing keys are preserved: only the URL keys this
 * script owns are rewritten, so hand-managed secrets in those files survive.
 *
 * Server-to-server calls (`API_URL`, `BILLING_API_URL`, `WIDGETS_API_URL`) stay
 * on loopback — those never leave the container and are deliberately untouched.
 *
 * Run directly (`pnpm dev:env`) or via the `pnpm dev*` scripts.
 */
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  HOST_TEMPLATE_ENV,
  previewOrigin,
  resolveHostTemplate,
  TUNNEL_DOMAIN_ENV,
  tunnelOrigin,
} from './dev-preview.mjs'
import { mergeEnvFile, readEnvValue } from './env-file.mjs'

const root = join(fileURLToPath(import.meta.url), '..', '..')

const PORTS = {
  app: 3000,
  enterprise: 3001,
  console: 3002,
  couriers: 3003,
  billing: 3004,
  invoice: 3006,
  crm: 3007,
  api: 4000,
}

const HEADER = '# Auto-generated by scripts/setup-dev-env.mjs — do not commit.'

/**
 * Billing makes server-only platform calls to resolve the signed-in user's
 * organization memberships. Those routes require the same internal key as the
 * core API, but each Next.js app loads only its own env files during local
 * development. Keep the Billing process in sync through its ignored local
 * override so enterprise users are not misclassified as unauthenticated.
 */
function syncBillingPlatformCredentials() {
  const apiEnvPath = join(root, 'apps', 'api', '.env')
  const internalKey = readEnvValue(apiEnvPath, 'API_INTERNAL_KEY')
  if (!internalKey) return false

  const billingEnvPath = join(root, 'apps', 'billing', '.env.development.local')
  mergeEnvFile(billingEnvPath, { API_INTERNAL_KEY: internalKey }, HEADER)
  return true
}

/** Keeps CRM's server-to-server credentials aligned across local env files. */
function syncCrmCredentials() {
  const platformEnvPath = join(root, 'apps', 'api', '.env')
  const appEnvPath = join(root, 'apps', '876', '.env')
  const crmApiEnvPath = join(root, 'apps', 'crm-api', '.env')
  const platformInternalKey = readEnvValue(platformEnvPath, 'API_INTERNAL_KEY')
  const platformAppKey = readEnvValue(appEnvPath, 'API_876_KEY')
  const crmInternalKey = readEnvValue(crmApiEnvPath, 'CRM_INTERNAL_KEY')
  let synced = false

  if (platformInternalKey || crmInternalKey) {
    mergeEnvFile(
      join(root, 'apps', 'crm', '.env.development.local'),
      {
        ...(platformInternalKey
          ? { API_INTERNAL_KEY: platformInternalKey }
          : {}),
        ...(crmInternalKey ? { CRM_INTERNAL_KEY: crmInternalKey } : {}),
      },
      HEADER
    )
    synced = true
  }

  if (platformAppKey) {
    mergeEnvFile(
      join(root, 'apps', 'crm-api', '.env.development.local'),
      { CRM_API_876_KEY: platformAppKey },
      HEADER
    )
    synced = true
  }

  return synced
}

/**
 * Per-app env keys this script owns, mapped to the port whose forwarded origin
 * they should carry. Keys absent from an app's map are never touched.
 */
function envPlanFor(origins) {
  return {
    876: {
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_ORG_URL: origins.enterprise,
      NEXT_PUBLIC_CONSOLE_URL: origins.console,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    enterprise: {
      NEXT_PUBLIC_ORG_URL: origins.enterprise,
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_CONSOLE_URL: origins.console,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    console: {
      NEXT_PUBLIC_CONSOLE_URL: origins.console,
      NEXT_PUBLIC_CONSUMER_URL: origins.app,
      NEXT_PUBLIC_BILLING_URL: origins.billing,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    couriers: {
      NEXT_PUBLIC_COURIERS_URL: origins.couriers,
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_BILLING_URL: origins.billing,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    billing: {
      NEXT_PUBLIC_BILLING_URL: origins.billing,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    invoice: {
      NEXT_PUBLIC_INVOICE_URL: origins.invoice,
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    crm: {
      NEXT_PUBLIC_CRM_URL: origins.crm,
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    // The API needs the forwarded origins on its CORS allow-list, and the
    // template so `scripts/seed_internal.py` can register matching OAuth
    // redirect/logout URIs for each app.
    api: {
      CORS_ALLOWED_ORIGINS: [
        'http://localhost:3000',
        'http://localhost:3001',
        'http://localhost:3002',
        'http://localhost:3003',
        'http://localhost:3004',
        'http://localhost:3006',
        'http://localhost:3007',
        origins.app,
        origins.enterprise,
        origins.console,
        origins.couriers,
        origins.billing,
        origins.invoice,
        origins.crm,
      ].join(','),
    },
    // Each product service keeps its own CORS allow-list. Only the app that
    // fronts it can reach it from a browser, so each list stays narrow.
    'billing-api': {
      CORS_ALLOWED_ORIGINS: ['http://localhost:3004', origins.billing].join(
        ','
      ),
    },
    'couriers-api': {
      CORS_ALLOWED_ORIGINS: ['http://localhost:3003', origins.couriers].join(
        ','
      ),
    },
    'storage-api': {
      CORS_ALLOWED_ORIGINS: [
        'http://localhost:3003',
        'http://localhost:3004',
        origins.couriers,
        origins.billing,
      ].join(','),
    },
  }
}

const tunnelDomain =
  process.env[TUNNEL_DOMAIN_ENV]?.trim() ??
  readEnvValue(join(root, '.env'), TUNNEL_DOMAIN_ENV)?.trim()
const template = resolveHostTemplate()

if (!template && !tunnelDomain) {
  const billingCredentialsSynced = syncBillingPlatformCredentials()
  const crmCredentialsSynced = syncCrmCredentials()
  console.log(
    '[setup-dev-env] No forwarded-port workspace detected — localhost defaults apply.'
  )
  if (billingCredentialsSynced)
    console.log(
      '[setup-dev-env] Synced Billing server credentials from apps/api/.env.'
    )
  if (crmCredentialsSynced)
    console.log('[setup-dev-env] Synced CRM server credentials.')
  process.exit(0)
}

const origins = Object.fromEntries(
  Object.entries(PORTS).map(([app, port]) => [
    app,
    tunnelDomain
      ? tunnelOrigin(app, tunnelDomain)
      : previewOrigin(port, template),
  ])
)

for (const [app, updates] of Object.entries(envPlanFor(origins))) {
  const path = join(root, 'apps', app, '.env.development.local')
  mergeEnvFile(
    path,
    {
      ...updates,
      ...(tunnelDomain
        ? { [TUNNEL_DOMAIN_ENV]: tunnelDomain }
        : { [HOST_TEMPLATE_ENV]: template }),
    },
    HEADER
  )
  console.log(`[setup-dev-env] Updated apps/${app}/.env.development.local`)
}

const billingCredentialsSynced = syncBillingPlatformCredentials()
const crmCredentialsSynced = syncCrmCredentials()
if (billingCredentialsSynced)
  console.log(
    '[setup-dev-env] Synced Billing server credentials from apps/api/.env.'
  )
if (crmCredentialsSynced)
  console.log('[setup-dev-env] Synced CRM server credentials.')

console.log(
  tunnelDomain
    ? `[setup-dev-env] Cloudflare Tunnel domain: ${tunnelDomain}`
    : `[setup-dev-env] Host template: ${template}`
)
for (const [app, origin] of Object.entries(origins)) {
  console.log(`[setup-dev-env]   ${app.padEnd(10)} ${origin}`)
}
