/**
 * Points every app's browser-visible dev URLs at the current workspace's
 * forwarded origins.
 *
 * On a plain local machine `http://localhost:<port>` is reachable from the
 * browser, so the committed `.env.development` defaults are correct and this
 * script exits without writing. Inside a remote workspace (GitHub Codespaces or
 * Ona/Gitpod) the browser is on a different machine, so each app's public URLs
 * must be the forwarded HTTPS origins instead — otherwise cross-app links,
 * browser-side SDK calls, OAuth redirects, and the API's CORS allow-list all
 * point at a localhost that only exists inside the container.
 *
 * Values land in each app's `.env.development.local` (gitignored, highest
 * precedence in Next.js). Existing keys are preserved: only the URL keys this
 * script owns are rewritten, so hand-managed secrets in those files survive.
 *
 * Server-to-server calls (`API_URL`, `BILLING_API_URL`, `WIDGETS_API_URL`) stay
 * on loopback — those never leave the container and are deliberately untouched.
 *
 * Run directly (`pnpm dev:env`) or via the `pnpm dev*` scripts.
 */
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  HOST_TEMPLATE_ENV,
  previewOrigin,
  resolveHostTemplate,
} from './dev-preview.mjs'
import { mergeEnvFile } from './env-file.mjs'

const root = join(fileURLToPath(import.meta.url), '..', '..')

const PORTS = {
  app: 3000,
  enterprise: 3001,
  console: 3002,
  couriers: 3003,
  billing: 3004,
  api: 4000,
}

const HEADER = '# Auto-generated by scripts/setup-dev-env.mjs — do not commit.'

/**
 * Per-app env keys this script owns, mapped to the port whose forwarded origin
 * they should carry. Keys absent from an app's map are never touched.
 */
function envPlanFor(origins) {
  return {
    876: {
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_ORG_URL: origins.enterprise,
      NEXT_PUBLIC_CONSOLE_URL: origins.console,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    enterprise: {
      NEXT_PUBLIC_ORG_URL: origins.enterprise,
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_CONSOLE_URL: origins.console,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    console: {
      NEXT_PUBLIC_CONSOLE_URL: origins.console,
      NEXT_PUBLIC_CONSUMER_URL: origins.app,
      NEXT_PUBLIC_BILLING_URL: origins.billing,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    couriers: {
      NEXT_PUBLIC_COURIERS_URL: origins.couriers,
      NEXT_PUBLIC_APP_URL: origins.app,
      NEXT_PUBLIC_BILLING_URL: origins.billing,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    billing: {
      NEXT_PUBLIC_BILLING_URL: origins.billing,
      NEXT_PUBLIC_API_URL: origins.api,
    },
    // The API needs the forwarded origins on its CORS allow-list, and the
    // template so `scripts/seed_internal.py` can register matching OAuth
    // redirect/logout URIs for each app.
    api: {
      CORS_ALLOWED_ORIGINS: [
        'http://localhost:3000',
        'http://localhost:3001',
        'http://localhost:3002',
        'http://localhost:3003',
        'http://localhost:3004',
        origins.app,
        origins.enterprise,
        origins.console,
        origins.couriers,
        origins.billing,
      ].join(','),
    },
  }
}

const template = resolveHostTemplate()

if (!template) {
  console.log(
    '[setup-dev-env] No forwarded-port workspace detected — localhost defaults apply.'
  )
  process.exit(0)
}

const origins = Object.fromEntries(
  Object.entries(PORTS).map(([app, port]) => [
    app,
    previewOrigin(port, template),
  ])
)

for (const [app, updates] of Object.entries(envPlanFor(origins))) {
  const path = join(root, 'apps', app, '.env.development.local')
  mergeEnvFile(path, { ...updates, [HOST_TEMPLATE_ENV]: template }, HEADER)
  console.log(`[setup-dev-env] Updated apps/${app}/.env.development.local`)
}

console.log(`[setup-dev-env] Host template: ${template}`)
for (const [app, origin] of Object.entries(origins)) {
  console.log(`[setup-dev-env]   ${app.padEnd(10)} ${origin}`)
}
