import type { CustomerTableRow } from '../_components/customers-table'

/** Frontend-only preview data for workspaces that do not have customers yet. */
export const FAKE_CUSTOMERS: CustomerTableRow[] = [
  {
    id: 'fake-customer-1',
    billingCustomerId: 'fake-billing-customer-1',
    customerName: 'Nia Campbell',
    companyName: 'Blue Mountain Trading',
    email: 'nia.campbell@example.test',
    phone: '+1 876 555 0101',
    mailboxNumber: '1001',
  },
  {
    id: 'fake-customer-2',
    billingCustomerId: 'fake-billing-customer-2',
    customerName: 'Andre Williams',
    companyName: null,
    email: 'andre.williams@example.test',
    phone: '+1 876 555 0102',
    mailboxNumber: '1002',
  },
  {
    id: 'fake-customer-3',
    billingCustomerId: 'fake-billing-customer-3',
    customerName: 'Sophia Brown',
    companyName: null,
    email: 'sophia.brown@example.test',
    phone: '+1 876 555 0103',
    mailboxNumber: '1003',
  },
  {
    id: 'fake-customer-4',
    billingCustomerId: 'fake-billing-customer-4',
    customerName: 'Marcus Thompson',
    companyName: 'Harbour View Imports',
    email: 'marcus.thompson@example.test',
    phone: '+1 876 555 0104',
    mailboxNumber: '1004',
  },
  {
    id: 'fake-customer-5',
    billingCustomerId: 'fake-billing-customer-5',
    customerName: 'Aaliyah Grant',
    companyName: null,
    email: 'aaliyah.grant@example.test',
    phone: '+1 876 555 0105',
    mailboxNumber: '1005',
  },
  ...[
    ['Daniel Foster', 'Kingston Office Supplies'],
    ['Maya Robinson', null],
    ['Jordan Clarke', 'Island Market Co.'],
    ['Zara Morgan', null],
    ['Ethan Lewis', 'Harbour Point Services'],
    ['Camille Scott', null],
    ['Noah Bennett', 'Blue Horizon Goods'],
    ['Amara Davis', null],
    ['Liam Wilson', 'Capital Courier Partners'],
    ['Grace Mitchell', null],
    ['Isaiah Moore', 'Seaside Retail Group'],
    ['Chloe Taylor', null],
    ['Nathan Anderson', 'Summit Business Centre'],
    ['Leah Thomas', null],
    ['Malik Jackson', 'Palm Grove Imports'],
    ['Sienna White', null],
    ['Caleb Harris', 'Kingston Trade House'],
    ['Ava Martin', null],
    ['Micah Young', 'Port Royal Distribution'],
    ['Layla King', null],
  ].map(([customerName, companyName], index) => ({
    id: `fake-customer-${index + 6}`,
    billingCustomerId: `fake-billing-customer-${index + 6}`,
    customerName,
    companyName,
    email: `${customerName.toLowerCase().replaceAll(' ', '.')}@example.test`,
    phone: `+1 876 555 ${String(index + 106).padStart(4, '0')}`,
    mailboxNumber: String(index + 1006),
  })),
]
