import { docs } from '@/.source/server'
import { loader } from 'fumadocs-core/source'

/**
 * The content source for the docs site. Wires the MDX collection generated by
 * `fumadocs-mdx` into Fumadocs' navigation tree under the `/docs` base path.
 */
export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
})
